### ISSUE TITLE
分组隔离问题

### ISSUE THREAD

**Issue by BennetWang** [KFCFans/PowerJob#102]
问一下，分组隔离。如果其中一个worker跟server网络抖动之后，导致这个worker选择了另外一台server，这样就有一个app两个server去管理，在这段时间内，怎么防止重复触发。我看到官网介绍说靠nextTriggerTime。但是我没看到更新nextTriggerTime加任何锁去控制并发。方便贴一下具体的代码位置吗？

其次，我发现worker选择server的有这么一段逻辑
 // 如果是本机，就不需要查数据库那么复杂的操作了，直接返回成功
        if (OhMyServer.getActorSystemAddress().equals(currentServer)) {
            return ResultDTO.success(currentServer);
        }
想问的是这样的逻辑，两个选择了不同server的worker是怎么最终选择同一个server的。我看worker的请求地址优先是先请求自己当前内存中存储的currentServer的，但是各自的currentServer可能不一致的。

**Comment by KFCFans** [comment]
1. 每次 server 调度前都会查询 DB 获取本机需要调度的任务，因此在每一个调度时刻每一个 AppName 下面的任务都只会被一台 server 调度。
![image](https://user-images.githubusercontent.com/9402086/99615167-e22b3000-2a55-11eb-82b9-e133e7f9d193.png)
代码详见：OmsScheduleService

2. worker 选择 server 这个确实是个 bug...当初加缓存的时候忘记考虑脑裂的情况了，这周末的版本更新里会 fix，感谢发现 BUG。

**Comment by BennetWang** [comment]
第一个问题，考虑一下，两个worker选择了不同的server。因为执行顺序的问题，原先的wroker选择了server1，然后加载了job信息。后面worker2切换了server2，也加载了job信息。这样不就会重复触发了吗？

**Comment by KFCFans** [comment]
数据库中的地址是唯一的，调度只可能由一台 server 进行。

**Comment by KFCFans** [comment]
你看我红框的那段逻辑

**Comment by BennetWang** [comment]
你考虑一下server1取出来之后变更了，然后server切换成server2， server2也取出来了。

**Comment by KFCFans** [comment]
哎你非得纠结那么极端的情况那谁也救不了你。

高可用和重复执行本来就是不可分割的两件事。
