### ISSUE TITLE
少了这两个jar包

### ISSUE THREAD

**Issue by ewsq** [KFCFans/PowerJob#104]
少了这两个jar包

        <dependency>
            <groupId>org.hibernate.javax.persistence</groupId>
            <artifactId>hibernate-jpa-2.1-api</artifactId>
            <version>1.0.2.Final</version>
        </dependency>

        <dependency>
            <groupId>javax.persistence</groupId>
            <artifactId>javax.persistence-api</artifactId>
            <version>2.2</version>
        </dependency>

**Comment by KFCFans** [comment]
JDK11 兼容性问题
