### ISSUE TITLE
jdk11 start powerjob-server error

### ISSUE THREAD

**Issue by zzps** [KFCFans/PowerJob#105]
**Describe the bug**
Error creating bean with name 'coreEntityManagerFactory' defined in class path resource [com/github/kfcfans/powerjob/server/persistence/config/CoreJpaConfig.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

**Environment**
 - PowerJob Version: [v3.3.2]
 - Java Version: [oracle jdk11]
 - OS: [CentOS 7.8]

**Comment by KFCFans** [comment]
JDK 11 删除了一些 JDK8 下的模块，需要自行添加相关的依赖。
这个错误很好解决，自己在网上搜索下就能解决，祝好运～

PS：最好在解决后能在这个 issue 下贴一下解决方法（估计就是2个 pom 配置），以便帮助其他人。

**Comment by KFCFans** [comment]
可以试试这个
https://github.com/KFCFans/PowerJob/issues/104

**Comment by zzps** [comment]
> 
> 
> JDK 11 删除了一些 JDK8 下的模块，需要自行添加相关的依赖。
> 这个错误很好解决，自己在网上搜索下就能解决，祝好运～
> 
> PS：最好在解决后能在这个 issue 下贴一下解决方法（估计就是2个 pom 配置），以便帮助其他人。

是的，所以我在根pom里面加了这个
`<dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.1</version>
        </dependency>
`
可以了，我是看官方文档说可以支持jdk11

**Comment by KFCFans** [comment]
是的，支持 JDK 11，不过开发环境是 JDK 8，所以在 JDK 11 下需要自己修修补补一些东西。

PS：没测试过了 Oracle JDK 的兼容性，不过只要能运行起来就没问题。
