### ISSUE TITLE
日志依赖MongoDB，可以切换到ES上面吗？

### ISSUE THREAD

**Issue by Link-Kou** [KFCFans/PowerJob#112]
日志依赖MongoDB，可以切换到ES上面吗？

我们没有用到MongoDB的需求场景。ES是有的。日志可以输出到ES上面吗？

**Comment by KFCFans** [comment]
有这个规划，日志持久化输出接口化，允许用户自定义存储介质。

短期内可以自己改下 powerjob-server 代码，应该不复杂。
