### ISSUE TITLE
部分展示方面优化建议

### ISSUE THREAD

**Issue by jjnnzb** [KFCFans/PowerJob#115]
**Is your feature request related to a problem? Please describe.**

- “近期失败任务数”中的“近期”定义明确一点是否更好？查询条件展示是不是更好？ 且切换到英文，页面依然展示“中国标准时间”（不太确定别的国家会显示成啥样）。
![image](https://user-images.githubusercontent.com/58833386/100497403-5c665d80-3196-11eb-8c36-0133499698cd.png)
![image](https://user-images.githubusercontent.com/58833386/100497495-dc8cc300-3196-11eb-9e9f-5538d78720e9.png)

- 告警信息里，目前是没有展示出appName，以及如果有多个worker，具体是哪个worker执行失败没展示，如果明确有执行机器的IP，展示出来是否更能帮助排查问题？

- 告警模块能否像PowerJob-Worker一样，不内嵌调用，例如调用三方的接口有频率限制的话，还需要为了这个模块多部署几份server。

**Comment by KFCFans** [comment]
1. “近期失败任务数” 其实是一个粗略的监控，可以考虑下希望有怎么样的监控，而不单单只是加个时间范围的简单优化。
2.1 appId -> appName 的转换可以考虑，包括枚举值数字的优化
2.2 com.github.kfcfans.powerjob.server.service.alarm.JobInstanceAlarm#taskTrackerAddress 就是执行器的 IP

3. “告警模块能否像PowerJob-Worker一样，不内嵌调用，例如调用三方的接口有频率限制的话，还需要为了这个模块多部署几份server” 没太懂，可以举个具体的例子细化下

**Comment by jjnnzb** [comment]
> 1. “近期失败任务数” 其实是一个粗略的监控，可以考虑下希望有怎么样的监控，而不单单只是加个时间范围的简单优化。
>    2.1 appId -> appName 的转换可以考虑，包括枚举值数字的优化
>    2.2 com.github.kfcfans.powerjob.server.service.alarm.JobInstanceAlarm#taskTrackerAddress 就是执行器的 IP
> 2. “告警模块能否像PowerJob-Worker一样，不内嵌调用，例如调用三方的接口有频率限制的话，还需要为了这个模块多部署几份server” 没太懂，可以举个具体的例子细化下

哈哈，主要我们用的内网最强的机器之一部署了PowerJob-server，它在的那个网段没法访问互联网，目前是在内网的另外一个网段部署了几个服务，给server这边调用的，走了Nginx配的负载均衡。这个看来就我们这边是这个情况，有需求我们自己定制化写吧。
