### ISSUE TITLE
首页英文介绍优化~

### ISSUE THREAD

**Issue by jjnnzb** [KFCFans/PowerJob#121]
## Question
首页介绍翻译感觉可以优化一下~
提供一下我的粗浅理解：
1. Enterprise job scheduling middleware with distributed computing ability.(企业级分布式调度与计算中间件)
思路：强调是企业级，定位是中间件，说明可靠性，也自然而然Powerful，另外分布式计算是PowerJob的特色，拿出来单独强调一下优势。整体比较简明。
2. Job scheduling middleware of the new generation, providing multiple strategies including openAPI, workflow support and distributed computing ability.(新一代任务调度中间件,提供openAPI等在内的丰富调度策略、支持工作流与分布式计算)
思路：强调是新一代的任务调度中间件，与同类产品比，有openAPI这种灵活的调度策略，另外支持工作流与分布式计算（介绍比较详细，讲了PowerJob各方面的优势。当然还有无锁设计，告警，都写似乎太多了点）。

**Comment by KFCFans** [comment]
选了第一条
