### ISSUE TITLE
如何增加业务日期的概念

### ISSUE THREAD

**Issue by cndavy** [KFCFans/PowerJob#123]
某些行业的任务大多要顺序执行 ，比如 日报 ，要顺序执行，参数中一般包括业务日期的概念，上一次业务日期结束后，自动进入本次业务日期任务的执行，等待事件触发后，执行本次任务，当前任务能获取到业务日期参数。目前Powerjob能实现这种任务调度？
谢谢。

**Comment by jjnnzb** [comment]
感觉不是新功能，目前OpenAPI就能满足。OpenAPI非常灵活的，参数通过instanceParams传过去就是了，可以在本次执行时候，再触发下次的任务，参数再按需求调整呀。还有workflow那种复杂的

**Comment by KFCFans** [comment]
@jjnnzb 说的很对，定制化的调度需求用 OpenAPI 去扩展和实现是最完美的方案。
