### ISSUE TITLE
关于是否能添加或者已经存在阻塞任务的功能

### ISSUE THREAD

**Issue by MAOUXSAKI** [KFCFans/PowerJob#125]
当前的最大实例数配置虽然能限制同时执行的任务实例数，但如果任务执行时间长的话同时也会生成大量的失败日志，是否能增加一个阻塞任务的选项，只要超过最大任务实例，就不会再生成任务，而是等上一个任务完成后再生成新的任务。

**Comment by MAOUXSAKI** [comment]
我确认了下，就算设置了最大实例数为1，但是到第三个实例才会报 too many instance的错误

**Comment by KFCFans** [comment]
> 我确认了下，就算设置了最大实例数为1，但是到第三个实例才会报 too many instance的错误

设为 0 才是不限制。

**Comment by KFCFans** [comment]
任务队列这个事情很早之前就提出来了，我也觉得有必要做，可以参考

https://github.com/KFCFans/PowerJob/issues/14

但是在不引入额外组件的情况下只用数据库实现会有点麻烦，也可能带来很大的性能开销，暂时还没有想到一个比较完美的方案。

**Comment by KFCFans** [comment]
这个 issue 先关闭了，具体进度在 #14  同步。
