### ISSUE TITLE
server端通过修改akka-port可以启动多个worker，在另外一台机器上启动worker成功，但是server端页面看不到机器，指定这个worker执行，也报no worker available

### ISSUE THREAD

**Issue by zhangjianpo** [KFCFans/PowerJob#126]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details. 

在另外一台机器上启动worker agent，在server端看不到
worker启动日志
![image](https://user-images.githubusercontent.com/13270989/101624277-ae3f9b00-3a54-11eb-93bc-62d0a2ee0b34.png)
worker到server端10086和7700端口都通
server到worker端27777端口通
server端起的两个worker可以看到
![image](https://user-images.githubusercontent.com/13270989/101624595-1a220380-3a55-11eb-8fbf-5b55985f1956.png)

**Comment by KFCFans** [comment]
请仔细阅读文档
![image](https://user-images.githubusercontent.com/9402086/101649792-3b471c00-3a76-11eb-9fcc-51594d573267.png)


https://www.yuque.com/powerjob/guidence/problem#xMQC9

**Comment by zhangjianpo** [comment]
server端ip：10.189.100.40
worker端ip：10.189.100.33，子网掩码：255.255.240.0
是在同一个局域网中的

**Comment by KFCFans** [comment]
贴下 worker 配置，还有 server 的日志。

no_worker_available 的时候 server 会输出一条 warn 日志，里面写了原因

**Comment by zhangjianpo** [comment]
warn日志：
 [Dispatcher-1|217243327391597248] cancel dispatch job due to no worker available, clusterStatus is appName:powerjob-agent-test,clusterStatus:{10.189.100.40:27778=SystemMetrics(cpuProcessors=12, cpuLoad=0.07, jvmUsedMemory=0.175, jvmMaxMemory=4.3682, jvmMemoryUsage=0.0401, diskUsed=46.6566, diskTotal=49.0905, diskUsage=0.9504, score=20), 10.189.100.40:27777=SystemMetrics(cpuProcessors=12, cpuLoad=0.07, jvmUsedMemory=0.143, jvmMaxMemory=4.3682, jvmMemoryUsage=0.0327, diskUsed=46.6566, diskTotal=49.0905, diskUsage=0.9504, score=20)}

指定了10.189.100.33这台worker执行
![image](https://user-images.githubusercontent.com/13270989/101717690-c3f7a380-3ada-11eb-8387-d6b6879a6945.png)

10.189.100.33worker启动日志
![image](https://user-images.githubusercontent.com/13270989/101717759-e25d9f00-3ada-11eb-9670-f565a37ef661.png)

**Comment by zhangjianpo** [comment]
![image](https://user-images.githubusercontent.com/13270989/101717881-1e90ff80-3adb-11eb-8dc6-159ff7ba4361.png)
两台机器的时间也同步过了

**Comment by KFCFans** [comment]
牛头不对马嘴啊。。。
你的 worker 使用的是 test 租户，所以你应该在 test 这个租户下建立任务啊。

![image](https://user-images.githubusercontent.com/9402086/101718098-847d8700-3adb-11eb-9f8e-537be5d4895f.png)

![image](https://user-images.githubusercontent.com/9402086/101718120-8cd5c200-3adb-11eb-9339-1bcd4ff21e42.png)

**Comment by zhangjianpo** [comment]
不好意思，我昨天后来又改了租户名称试试的，忘记启动命令改回来了，抱歉抱歉

**Comment by zhangjianpo** [comment]
耽误大神时间，抱歉，我分析可能和系统时间不一致有关，因为昨天是powerjob-agent-test这个租户起的，今天只做了同步server和worker的时间操作，两台机器的时间相差几分钟

**Comment by KFCFans** [comment]
哈哈你太客气了，有问题提出来就好，在 GitHub 上的我都会认真解答。

如果正式使用了，欢迎填个接入登记哦～
