### ISSUE TITLE
真实的最大实例数要比设置的最大实例大1

### ISSUE THREAD

**Issue by MAOUXSAKI** [KFCFans/PowerJob#127]
![image](https://user-images.githubusercontent.com/54871762/101706057-496f5980-3ac3-11eb-8f07-640bcdc32c95.png)
最大实例数设置为1的时候也会同时存在两个实例，在第三个实例生成时才会报 too much instance 2 > 1的错误。
当我把com.github.kfcfans.powerjob.server.service.DispatchService 中的 `runningInstanceCount > maxInstanceNum` 改为`runningInstanceCount >= maxInstanceNum` 才表现正常。在生成第二个任务实例是就会报错了。
该问题是在 v3.3.3版本中发现的。

**Comment by KFCFans** [comment]
不错，很细心。
既然发现错误并找到解决方案了，可以提个 PR 修复～
这样你就可以成为项目的贡献者了。

**Comment by MAOUXSAKI** [comment]
> 不错，很细心。
> 既然发现错误并找到解决方案了，可以提个 PR 修复～
> 这样你就可以成为项目的贡献者了。
![image](https://user-images.githubusercontent.com/54871762/101739651-cbcb3e00-3b02-11eb-862d-170f925a8951.png)

我看了那块代码的注释，感觉本意应该是想把当前待分配的任务也算作running状态去进行处理，也就是说如果按照注释部分的设计意图来看的话，当第二个实例生成的时候这里的runningInstanceCount应该是2，但实际上由于统计或者状态变化没有按照预期的去更改，导致了第二个实例在运行这段代码的时候runningInstanceCount还是1。我这样改只是以结果来看是对的。但是不知道是否符合最开始的设计意图。

**Comment by KFCFans** [comment]
我周末空了仔细看下，感谢你的认真分析！

**Comment by KFCFans** [comment]
判断逻辑没问题。

不过用控制台点立即运行时确实会存在超出设定实例数的问题。
原因是 dispatch 时没有加锁去保证数据的安全性（没有很大的必要，毕竟正常调度情况下不会出现并发问题）。

所以这个问题基本不算是问题，选择不处理～

**Comment by MAOUXSAKI** [comment]
我这边不是立即运行导致的这个问题，用的是cron job，但是如果实例本身发现自己要执行操作就会导致之前的那个实例还没有完成cron 又触发了，新的这个实例就会多出来。

**Comment by MAOUXSAKI** [comment]
![image](https://user-images.githubusercontent.com/54871762/102037338-e271dd80-3dff-11eb-826c-d810ef1148c6.png)

v3.3.3版本中如果该任务是由cron生成的，那么在图上那一步进行统计的时候，我这边发现，当前instance的状态为WAITING_DISPATCH，而不是图中的WAITING_WORKER_RECEIVE或者RUNNING，所以就会导致统计出问题
