### ISSUE TITLE
[BUG] bug report

### ISSUE THREAD

**Issue by flyshadowhan** [KFCFans/PowerJob#13]
Hi,偶然发现你的项目,对你的项目很感兴趣,发现了几个问题:
1.现有的几个release版本都无法编译成功.具体可以查看附件.不知有何解决办法?
[compile-log.txt](https://github.com/KFCFans/PowerJob/files/4841606/compile-log.txt)
2.语雀的文档有小错误.
![a](https://user-images.githubusercontent.com/20167182/85936313-1168c580-b92c-11ea-81aa-a707e7bee8a6.png)

万望不吝赐教

**Comment by KFCFans** [comment]
看了下编译失败的日志，似乎是 release 2.0.0 版本的，当时处于项目更名的动荡期，存在一些潜在的问题也是有可能的，所以推荐你使用最新代码（master分支或 [release 3.1.2](https://github.com/KFCFans/PowerJob/releases/tag/v3.1.2)），然后使用`mvn clean package -Pdev -DskipTests`进行编译，理论上应该能成功通过编译。如果有问题可以继续report～

非常感谢你能帮助指出文档中的错误，已修正！
