### ISSUE TITLE
真实的最大实例数要比设置的最大实例大1 实际原因

### ISSUE THREAD

**Issue by MAOUXSAKI** [KFCFans/PowerJob#132]
https://github.com/KFCFans/PowerJob/issues/127#issue-760786037
![image](https://user-images.githubusercontent.com/54871762/102038142-72fced80-3e01-11eb-9b03-de7ae536eb76.png)
v3.3.3版本中如果该任务是由cron生成的，那么在图上那一步进行统计的时候，我这边发现，当前instance的状态为WAITING_DISPATCH，而不是图中的WAITING_WORKER_RECEIVE或者RUNNING，所以就会导致统计出问题。所以就会导致在进行最大instance判断时，实际的要比统计的大1

**Comment by MAOUXSAKI** [comment]
我看了下历史，7月14号前都用的是generalizedRunningStatus这个变量。之后就改成了现在这个样子。
![image](https://user-images.githubusercontent.com/54871762/102038671-d63b4f80-3e02-11eb-9f9a-758a0f976ddb.png)

**Comment by KFCFans** [comment]
改动的原因是：
如果存在大量 OpenAPI 触发的延迟任务，dispatch 阶段根据 WAITING_WORKER_RECEIVE 和其他状态统计出的数量一定会超过 max_instance_num，从而导致任务不能正常派发。

**Comment by KFCFans** [comment]
目前看来对于非常高频的执行任务，PowerJob 不做非常精准的卡点。
毕竟执行频率能那么高的任务多执行几次影响也不是很大。
