### ISSUE TITLE
关于server 同步到mvnrepository

### ISSUE THREAD

**Issue by ChuanZhang117** [KFCFans/PowerJob#138]

**Comment by KFCFans** [comment]
server 不需要被依赖，不会上传 jar 到中央仓库。如果需要 jar 文件，可以自己打包或者在 https://github.com/KFCFans/PowerJob/actions 中选择 JAVA CI With Maven 完成下载。

![image](https://user-images.githubusercontent.com/9402086/103120211-c7318880-46b1-11eb-9309-04b49aaca44f.png)
