### ISSUE TITLE
Swagger version should be up-to-date with pom version.

### ISSUE THREAD

**Issue by jjnnzb** [KFCFans/PowerJob#139]
As is shown as follows, Swagger version is set as 3.3.0, yet pom version is now 3.4.1. 

![image](https://user-images.githubusercontent.com/58833386/103127752-ce668f80-46cd-11eb-967e-ba46f62a549d.png)

![image](https://user-images.githubusercontent.com/58833386/103127783-e2aa8c80-46cd-11eb-95ce-f57c5be6d235.png)

**Comment by KFCFans** [comment]
暂时没想到能动态获取的方法，你可以研究下然后提个 PR 哈哈～

**Comment by KFCFans** [comment]
好像可行，找了个教程，你可以试试～

https://stackoverflow.com/questions/38983934/cannot-get-maven-project-version-property-in-a-spring-application-with-value
