### ISSUE TITLE
对注释有点疑问

### ISSUE THREAD

**Issue by ocean23** [KFCFans/PowerJob#140]
![WechatIMG1476](https://user-images.githubusercontent.com/8874638/103133496-b69b0580-46e5-11eb-9048-70701679e462.png)
![WechatIMG1475](https://user-images.githubusercontent.com/8874638/103133499-ba2e8c80-46e5-11eb-884d-661f9c3527f5.png)

根据我对`response.sendRedirect(url);`的理解是服务器通知浏览器再次请求转发的地址，这里也应该会有二次请求所以感觉这里用httpClient之类的工具请求目标服务器获取到结果再返回给前端性能上应该差不多，可能由于没有浏览器的参与性能可能会好一点点，不知道理解的正不正确，假如不正确希望指正，谢谢了！

**Comment by KFCFans** [comment]
* server 内部转发，转发的是具体内容（返回的日志数据）
* server 通知浏览器转发，转发的只是请求

当实际返回数据包很大时，两者有明显的性能差距（前者需要在网络中传输2次大数据包：serverA ->  serverB -> browser）

PS：新版本该代码已经被移除了，统一使用 server 内部转发的方式来优化代码。你这个 issue 算为这段代码留了个记念，哈哈。

**Comment by ocean23** [comment]
是哦，我怎么忘记了重定向只是转发请求，感谢提醒，学习了。
我为什么会看这个重定向的问题是因为现在我们是用k8s部署的powerJob，而我访问的其中一个server端的web页面时选择其中一个instance而这个instance所属task的currentServer不是当前我访问的server端时它用触发一个重定向，但是由于重定向是生产环境容器内网的一个ip，在我没有vpn到生产环境时我的电脑是访问不了这个容器内的ip这时就会导致一个timeout的错误，我还专门在部门的wiki上写了要看日志的话要vpn后再看，不然就会触发钉钉监控的告警:sweat_smile:，想不到新的版本这么快就解决了:+1:
越用powerjob越喜欢这个项目，希望慢慢熟悉它的代码后能够参与到这个项目中来。

**Comment by KFCFans** [comment]
哈哈，期待哦～

**Comment by KFCFans** [comment]
对了，有很多人对 PowerJob 在 k8s 上的部署有疑惑。
如果你有兴趣的话，可以发个博客出个教程什么的，指导一下别人～

**Comment by ocean23** [comment]
我让运维同事帮忙部署的:joy:

**Comment by KFCFans** [comment]
> 我让运维同事帮忙部署的😂

哈哈，问题不大～

**Comment by ocean23** [comment]
我看了v3.4.1版本的实现，现在的调用方式如下图的新方案，对比旧的方案不考虑其他方面单从传输"大"数据包的角度看，是不是旧方案更有效率一点，因为它只需要传输一次。

![redirect_akka](https://user-images.githubusercontent.com/8874638/103262678-a1252480-49e0-11eb-9dd4-d2e9a192701b.png)

**Comment by KFCFans** [comment]
是的，这就是那句注释的含义，原来的方式很高效，但是有一些缺点：
1. 不算BUG的BUG：要求用户网络能访问生产网络，否则重定向后无法访问
2. 要求所有 server 的端口一致，否则无法访问
3. 代码不够简介，无法统一抽取转发层

由于日志查看并不需要在意性能问题，因此选择低效但优雅但方式。

**Comment by ocean23** [comment]
明白，感谢回复:+1:
