### ISSUE TITLE
任务多开关几次，调度中心的worker机器都不见了

### ISSUE THREAD

**Issue by iLinuxs** [KFCFans/PowerJob#143]
新建了一个FIX_RATE 6000的任务
<img width="1791" alt="WX20201229-213249@2x" src="https://user-images.githubusercontent.com/14077439/103291275-efa4e400-4a1d-11eb-8d47-963ee400b3a4.png">
启动执行一段时间没啥问题，worker也是正常的
<img width="1791" alt="WX20201229-210442@2x" src="https://user-images.githubusercontent.com/14077439/103291391-2d097180-4a1e-11eb-99e5-cab40e788fa1.png">
但是任务多次开启、关闭之后，发现调度中心的worker机器都消失了
<img width="1791" alt="WX20201229-210527@2x" src="https://user-images.githubusercontent.com/14077439/103291483-66da7800-4a1e-11eb-93c6-eed3b866d0f8.png">

**Comment by KFCFans** [comment]
找下日志，光靠一个图没办法定位问题。
