### ISSUE TITLE
多实例下的server每晚定时清理日志时可能会并发问题

### ISSUE THREAD

**Issue by ocean23** [KFCFans/PowerJob#144]
**错误日志**
```
[GridFsManager] deleted log#5fe242297211c2739d327b1e failed.

com.mongodb.MongoGridFSException: No file found with the id: BsonObjectId{value=5fe242297211c2739d327b1e}
	at com.mongodb.client.gridfs.GridFSBucketImpl.executeDelete(GridFSBucketImpl.java:403)
	at com.mongodb.client.gridfs.GridFSBucketImpl.delete(GridFSBucketImpl.java:378)
	at com.mongodb.client.gridfs.GridFSBucketImpl.delete(GridFSBucketImpl.java:373)
```

我看了一下代码发现这个`CleanService`里面有一个spring的定时器`@Scheduled(cron = CLEAN_TIME_EXPRESSION)`然后报错由于以下语句导致的
```
        // 删除 GridFS 过期文件
        cleanRemote(GridFsManager.LOG_BUCKET, instanceInfoRetentionDay);
        cleanRemote(GridFsManager.CONTAINER_BUCKET, remoteContainerRetentionDay);
```
有一个地方想不明白，由于我们是部署了多个server端，假如直接用`Spring`的`Scheduled`那每一个server端凌晨3点时都会执行mongodb的操作，那当一条记录同时被两个server端查出来，但是第一个server端已经把这条记录删除，第二个server端再去删这条记录时就会报上面这个错误。不知道我理解的对不对？假如我理解不正确的地方麻烦指出一下，谢谢了:smile:

**Environment**
 - PowerJob Version: [e.g. 3.4.1]
 - Java Version: [e.g. OpenJDK 11]
 - OS: [e.g. CentOS 8.1]

**Comment by KFCFans** [comment]
确实这块没考虑多 server 并发删除的问题。
感谢发现问题～

**Comment by ocean23** [comment]
我想想怎么优化准备在这个项目提第一个PR :grimacing:

**Comment by KFCFans** [comment]
哈哈，好。
那这个任务就交给你了！

**Comment by ocean23** [comment]
:ok_hand:

**Comment by KFCFans** [comment]
这个是不是也是老版本的代码？
我看新版本已经全面使用 deleteBefore 了，只是会有多余的删除操作，但不会报错。

**Comment by ocean23** [comment]
我刚刚确认了在V3.4.1和master分支`GridFsManager`类都还是用`bucket.delete(objectId);`
<img width="1179" alt="bucket" src="https://user-images.githubusercontent.com/8874638/103356174-27c62880-4aeb-11eb-8fa0-061f7e90a031.png">

**Comment by ocean23** [comment]
@KFCFans 你指的`deleteBefore`是以下这个截图的红框吗？
<img width="1020" alt="deleteBefore" src="https://user-images.githubusercontent.com/8874638/103390199-1b26ec00-4b4e-11eb-9ce6-1abcda703e14.png">

**Comment by KFCFans** [comment]
哈哈，你理解是对的。我昨天就随便在 GitHub 看了眼代码。

这一块逻辑很久没动了，都有点忘了hhh。

**Comment by ocean23** [comment]
今天想了一下没想到什么好的办法，唯一想到的方案是把`bucket.delete(objectId);`语句遇到not found时把这个错误吃掉不打error日志，不然每天晚上钉钉都会收到一堆错误告警 @KFCFans 你有没有什么好的方向改进，有好的方向我再负责具体的代码:smile:

**Comment by KFCFans** [comment]
分布式锁
锁的实现已经有了，可以用下锁。

**Comment by ocean23** [comment]
因为对powerjob的代码还不是很熟悉，刚刚看了一个源码是用这个`DatabaseLockService`基于数据库实现的分布式锁吗？

**Comment by KFCFans** [comment]
> 因为对powerjob的代码还不是很熟悉，刚刚看了一个源码是用这个`DatabaseLockService`基于数据库实现的分布式锁吗？

是的。
拿到锁执行，拿不到锁放弃执行就行。

**Comment by ocean23** [comment]
:ok_hand:

**Comment by ocean23** [comment]
已发PR
