### ISSUE TITLE
希望在任务流中新增各个子任务日志

### ISSUE THREAD

**Issue by xjxjin** [KFCFans/PowerJob#16]
在任务流中新增一个日志按钮，查看各个任务的详细日志信息

**Comment by KFCFans** [comment]
工作流只是任务的一种调度形式，工作流中的所有任务实例，都能在 “任务实例” 页面的工作流实例能找到
我不知道你说的任务的详细日志信息是什么？
如果是任务实例的详细信息，点击工作流详情的节点就能查看。
如果是在线日志，那么去 “任务实例” 页面的工作流实例 TAB，根据任务实例 ID 搜索，能够查到该条任务实例，点击日志即可查看。（该步骤确实有些繁琐，等待社区contribute中，我目前主要方向还是在框架稳定性和基础功能完善上，前端毕竟是辅助作用，暂时“能用就行”，望体谅！）
