### ISSUE TITLE
[Feature] ServerSelectService选举优化

### ISSUE THREAD

**Issue by MidnightFiend** [KFCFans/PowerJob#17]
**Is your feature request related to a problem? Please describe.**

因为server集群为 多主 + 先到先得的选举模式。

如果把PowerJob作为 团队 所有定时任务的管理平台。

AppId多了后，糟糕的情况，可能某一个server节点会成为大多数AppId的Leader。

导致server间负载过度倾斜。

**Describe the solution you'd like**

方案1：
竞选前，通过SQL-count统计instance近1小时的调度量，推举承载instance最小且isActive的server节点为Leader

方案2：
server_info表增加负载、上报时间字段，当前server节点定时上报自己状况。
一旦某AppId需要选举，则通过查表找到最近有上报&负载最轻的节点，转发选举请求（如果最轻就是自己，则立刻参选）

**Describe alternatives you've considered**

**Additional context**

**Comment by MidnightFiend** [comment]
不过，感觉这不是当前需求

**Comment by KFCFans** [comment]
首先，非常感谢您的建议！

server压力偏斜这个问题确实是存在的，我以前也仔细考虑过，不过出于以下几点原因，目前没有考虑解决这个“问题：

1. powerjob-server只负责任务的调度，再加上时间轮等设计，调度性能很好，单台机器能够支撑的任务总量非常可观。再加上随机选主策略，非极端情况应该是不会到达性能调度瓶颈的。

2. 竞选 leader 的策略其实是本机优先，而如果公司内部作为平台部署的话，肯定是用域名去代替ip，那么域名到ip这一层应该是自带 LB 的，也就是通过DNS LB 能解决server偏斜的问题。

当然啦，框架本身是追求完美的，这个偏斜问题等框架足够稳定（当然现在已经很稳定了）、用户合理需求支持足够完善后，我会找机会解决。这个过程可能漫长～

从您能提出这个问题就能看出，您对 PowerJob 的原理和源码应该都足够熟悉了，如果有兴趣，也欢迎为项目做贡献～

以上

**Comment by MidnightFiend** [comment]
单机能解决大多问题是可信的，大部分场景也确实用不上这个feature。

但DNS LB并不能保障server倾斜问题，引发选举的 /acquire请求，到达哪个server节点完全是随机的。

**Comment by KFCFans** [comment]
确实，单纯 DNS LB 是完全随机的，刚刚表述有误。
不过在数据量足够多的情况下，随机在概率论上就是均匀分布的。
而 powerjob-server 的单点足够强。
因此实际情况下应该是很难出现由于偏斜而导致的性能问题的。大体上还是会均匀分布。

补充一点刚刚想起来的原因：
appid数并不能完全反映负载情况，有些业务下面看就一两个任务几个机器，有些业务则成百上千的任务几百上千机器，很难量化。
