### ISSUE TITLE
[Feature] feature request

### ISSUE THREAD

**Issue by MidnightFiend** [KFCFans/PowerJob#18]
**Is your feature request related to a problem? Please describe.**

对 TimeExpressType.CRON 的JobInfo

在本该触发的 nextTriggerTime 左右，恰好遭遇 宕机/停机/长GC停顿 跳过了，则CRON表达式的下一次触发时间，也server也无法SQL扫描出这条“错过刷新时机”的Job。

恰好我们团队之前定时也用的类似扫描方式，生产环境遭遇过“错过刷新时机”的问题，而该定时任务的需求是用户添加的，量大无法人力检查。

不知道这个问题 PowerJob version 3.1.3 是否存在

**Describe the solution you'd like**

之前的解决方式是增加一个线程每分钟扫描 Status.enable & 触发时间是 beforeNow 的。

当然这个补丁不太优雅。

**Comment by KFCFans** [comment]
PowerJob 不存在这个问题。

PowerJob 只有成功写入任务实例运行日志后才会修改 job 表的 next trigger time。而一旦写入任务实例运行日志表，就会有各种机制保障调度的进行。

**Comment by MidnightFiend** [comment]
Thanks，SQL没看仔细
