### ISSUE TITLE
[Feature] 支持定制表前缀

### ISSUE THREAD

**Issue by dudiao** [KFCFans/PowerJob#19]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
可否考虑所有PowerJob表，统一加上表前缀（比如pj_），以便于和其他业务表进行区分。

大概看了下，通过以下两步可以实现：
1. 继承`ImplicitNamingStrategyJpaCompliantImpl`类；
2. 修改`@Query(nativeQuery = false)`和其SQL

**Comment by KFCFans** [comment]
业务的其他表应该不会使用 powerjob 的专用数据库吧，个人认为数据库的隔离就足够了。

当然，加上 pj_ 前缀会显得比较规范和好看，不过出于兼容性考虑，应该不会在正式代码中更改。

**Comment by dudiao** [comment]
我们公司有些场景，所有的表都在一起的，比如单体服务：系统管理、业务、调度，都用的一个数据库，没有前缀，找起来比较麻烦

**Comment by KFCFans** [comment]
我是建议 powerjob 使用单独的数据库...毕竟如果调度的任务多了，对 DB 的压力其实是不小的。

你们公司是不能创建新的数据库吗？否则为 powerjob 单独创建一个库不就行了...一条 SQL 的事情。

最后，如果实在不行的话，只能麻烦你自己修改源码了...毕竟改数据库表名涉及到重大的版本兼容性问题，会导致已经接入且上线的公司没办法平滑升级到新版本，所以没办法适配，抱歉。

**Comment by dudiao** [comment]
刚刚漏说了，兼容性的问题，可以默认不加前缀，这样就能平滑迁移了。

**Comment by KFCFans** [comment]
是那种交付给客户的产品吗？整个源码和DB部署方案一起打包交过去的那种？

哎，你这个需求提的晚了点。要是在改名那段时间提，二话不说我就给你支持了。现在真的是船大难掉头了...

我暂时想不到优雅的自定义表名方案（nativeSQL 那里只能 if else 判断），所以选择暂时不支持...抱歉...

不过你倒是提醒了我，nativeSQL的弊端，在后续版本我会考虑移除 nativeSQL，这样自定义表名只需要修改所有DO上面的@Table注解，成本就很低～

PS：有兴趣的话这个需求你可以开发下，哈哈哈～

**Comment by dudiao** [comment]
就是那种交付给客户的产品！！

**Comment by KFCFans** [comment]
if else 那种兼容就放弃吧...我不会合并的...

兼容这东西其实就是牺牲长远牺牲未来的事情，在没什么必要的情况下我不会去用。

我觉得出路在于把 JPA 的 nativeSQL 全部改掉，即用对象名和属性名代替表名和数据库字段名，这样接入方想改表名的成本就很低，也能解决你的问题。

**Comment by KFCFans** [comment]
since v3.2.0
