### ISSUE TITLE
Bug Report 点击运行出现2次任务

### ISSUE THREAD

**Issue by xjxjin** [KFCFans/PowerJob#23]
**Describe the bug**
在任务管理中点击运行任务，在任务实例中普通任务实例出现2条任务，多次测试确认不是手抖缘故，没有创建工作流
![1](https://user-images.githubusercontent.com/35513148/88127211-bc0b9580-cc05-11ea-995a-bb0c0d0873ed.png)
![2](https://user-images.githubusercontent.com/35513148/88127224-c037b300-cc05-11ea-9f2a-6e80b632a4fa.png)
![3](https://user-images.githubusercontent.com/35513148/88127231-c29a0d00-cc05-11ea-9f77-86943867595c.png)

**Comment by xjxjin** [comment]
刚刚测试，使用火狐浏览器，点运行正常，使用谷歌浏览器无痕模式点击正常，将谷歌浏览器缓存全部清除，登录点击还是会出2次，而且还会偶尔出现执行错误任务，错误内容为运行结果: too much instance(2>1)，测试电脑为macPro，谷歌浏览器版本为版本 84.0.4147.89（正式版本） （64 位）

**Comment by KFCFans** [comment]
经过我自己的反复测试和你的描述（其他浏览器能成功），我觉得这应该不是 PowerJob 的BUG。
这部分逻辑也非常简单，你可以顺着 Controller 进去看源码，不至于会有这种神奇的 BUG。

建议在能复现的浏览器打开网络监视器，点击运行后观察发送给 powerjob-server 的请求，如果出现2个请求，那么就确定不是 PowerJob 的问题了。
