### ISSUE TITLE
Bug shell 执行完毕 日志里面顺序乱序

### ISSUE THREAD

**Issue by xjxjin** [KFCFans/PowerJob#24]
shell执行完毕 日志不是顺序打印，能否调整下顺序保存日志
![image](https://user-images.githubusercontent.com/35513148/88138085-8c698700-cc1f-11ea-9d03-7e00eb274eed.png)

**Comment by KFCFans** [comment]
这确实是个 bug，理论上应该是按时间排序的。即同一毫秒内可能乱序，但不同毫秒内应该是有序的。

感谢反馈，我会处理的～

**Comment by KFCFans** [comment]
这应该是任务运行中出现的问题，且在一定时间（1分钟）后会自动修复，任务运行完成后的最终日志应该也不会出现这个问题。你可以确认下。

在任务运行过程中，由于网络延迟等原因，难免出现先后不一致行为。

**Comment by xjxjin** [comment]
这是执行完毕后我等待三分钟下载的日志，还是会乱序
![image](https://user-images.githubusercontent.com/35513148/88242943-5ed51a00-ccc1-11ea-9dba-31153476b555.png)

**Comment by KFCFans** [comment]
应该不是代码的问题...
can't fix......
