### ISSUE TITLE
Feature 新增运行的api接口

### ISSUE THREAD

**Issue by xjxjin** [KFCFans/PowerJob#25]
页面的运行按钮可否另外提供一个api出来，公司目前采用的是jenkins 自动化部署流程，部署完毕会自己启动任务，目前的想法的是部署完毕后使用jenkins 调用运行接口，然后在页面看执行情况

**Comment by KFCFans** [comment]
本来就有 OpenAPI。
powerjob-client 就是干这事的。
详见文档：https://www.yuque.com/powerjob/guidence/olgyf0

如果需要 HTTP 接口，可以查看 client 的实现细节，内部封装的就是 HTTP 请求与处理逻辑。
