### ISSUE TITLE
ui首页刷新报no appId问题

### ISSUE THREAD

**Issue by 745819123** [KFCFans/PowerJob#26]
**Describe the bug**
ui首页每次刷新都会报no appId，还有个问题，建议不要将密码存在localStorge里面，可以改用jwt之类的token

**Comment by KFCFans** [comment]
1. 控制台刷新本来就是不合法操作，正常使用不应该刷新
刷新以后的逻辑是：刷新结束 -> 页面重新获取数据，但是由于刷新后 vuex 存储的 appId 消失了，导致请求不合法 -> 前端拦截请求，强制退出登陆 -> 登陆界面监测到账号信息，自动登陆

2. 这个毕竟不是对外系统，内部系统的权限啊安全啊没必要那么较真。
毕竟有着网络隔离这一层天然屏障。

**Comment by KFCFans** [comment]
鉴于多个用户反馈 no appId 这个问题，下个版本将去掉这个提示...

怪我低估了用户对错误提示的敏感程度。

**Comment by KFCFans** [comment]
since v3.2.2
