### ISSUE TITLE
docker容器中运行powejob-server，woker端会报连不上akka

### ISSUE THREAD

**Issue by 745819123** [KFCFans/PowerJob#27]
**Describe the bug**
docker容器中运行powejob-server，woker端会报连不上akka，通过日志查看，是因为akka连接到容器内部ip和端口了，目前解决办法：docker容器网络改成host模式，但是k8s平台就不行了

建议：增加显示配置akka的ip和端口

**Comment by KFCFans** [comment]
1. PowerJob 系统的运行条件本来就是所有组件都必须在一个局域网内，如果用 Docker 部署，那么 server 和 worker 都必须在同一个 docker bridge 中。
2. k8s就更加没问题了，k8s基础的网络模型是所有pod都在一个可以直接连通的、扁平的网络空间中，自然可以相互访问

回复建议：这个不是增加配置的问题，由于 server 和 worker 需要相互通讯，唯一的办法就是在同一个局域网内。就算增加 worker 配置让它能主动连上 server，server 也无法将信息传递到 worker（因为 worker 的地址需要 worker 自己上报上去，而应用只能获取自己的内网地址）。

**Comment by KFCFans** [comment]
k8s 这一块我没实践过，如果你有实际场景，欢迎反馈～

不过我觉得 docker 也好，k8s也好，应该是不需要针对这些场景去特殊编程，它们应该提供了解决方案。即，正常场景下能跑的代码，docker + k8s 上肯定有办法直接跑

**Comment by 745819123** [comment]
主要是有些希望一套系统管理所有调度任务，但是子系统很多，有些在k8s里面，有些在虚拟机里面；
而且测试也不方便。

**Comment by KFCFans** [comment]
看了这篇文章：https://developer.aliyun.com/article/745468

我没理解错的话，k8s 中所有 pod 可以相互访问，pod 内的 docker 容器**拥有 pod 的IP 和 port**，这样就不存在网络隔离的问题了，可以相互访问。

**Comment by KFCFans** [comment]
你描述的问题，我个人认为属于你们公司网络规划的问题......

而且虚拟机还是 k8s 都没关系，只要配置好网络，在一个局域网内就行。

**Comment by 745819123** [comment]
是的，在相同环境里面没有问题，k8s里面有dns服务的，可以通过服务名称相互访问，ip每次重启都会改变，这个还没有测试有没有问题；
我刚才反馈的意思是，现在测试环境也在k8s，但是我本机想连接上去调试就不行，就是说我的server和我本机必须在同一个局域网才行；
k8s的服务暴露是通过service实现的，和虚拟机通讯也是通过service；而应用拿到的是pod的ip，就没办法通讯了

**Comment by KFCFans** [comment]
k8s 内肯定是可以通过 IP 通讯的，否则像 dubbo 这种怎么玩呢？

本机连上去测试也是你们网络环境的问题，日常环境和办公网络就应该是可以互通的啊...

**Comment by Garyoook** [comment]
@745819123 , 请问你是具体如何解决woker端连不上akka的问题的呀, 我尝试在server端docker启用了host模式但是导致浏览器无法进入dashboard

**Comment by GoneGo1ng** [comment]
@KFCFans 我把powerjob-server部署在k8s上使用的时候也遇到了这个问题，那么多issues里都提到了这个问题，我觉得你应该把powerjob-server在k8s上部署一遍，试一下。你会发现确实有一些坑的存在。

下面是我的两点建议，希望对powerjob-server在k8s上的使用有帮助：
1. 能否将这个参数`-Dpowerjob.network.local.address`改成可以指定域名 
2. 服务发现接口`DISCOVER_URL = "http://%s/server/acquire?appId=%d&currentServer=%s&protocal=AKKA"`获取的地址能否改成可以手动配置

**Comment by midaug** [comment]
> @KFCFans我的powerjob-server部署在k8s上部署的时候也遇到了这个问题，有几个问题里都说了这个问题，我应该把powerjob-server在k8s上部署，试一下。你会发现确实有一些坑的存在。
> 
> 下面是我的两点建议，希望对powerjob-server在k8s上的使用有帮助：
> 
> 1. 能否将这个参数`-Dpowerjob.network.local.address`改成可以指定域
> 2. 服务发现接口`DISCOVER_URL = "http://%s/server/acquire?appId=%d&currentServer=%s&protocal=AKKA"`中获取的地址能否改成可以手动配置，地址是指返回参数中的数据`{"success": true,"data": "10.42.0.13:10086","message": null}`

我碰到了相同问题，在mac的docker中部署powerjob-server使用参数`-Dpowerjob.network.local.address`指定为主机ip会出现
[oms-server-akka.actor.default-dispatcher-5] ERROR akka.io.TcpListener - Bind failed for TCP channel on endpoint [/10.43.13.123:10086]
pjons2    | java.net.BindException: [/10.43.13.123:10086] Cannot assign requested address


期望采纳上面建议

**Comment by starchen-jnu** [comment]
> @KFCFans 我把powerjob-server部署在k8s上使用的时候也遇到了这个问题，那么多issues里都提到了这个问题，我觉得你应该把powerjob-server在k8s上部署一遍，试一下。你会发现确实有一些坑的存在。
> 
> 下面是我的两点建议，希望对powerjob-server在k8s上的使用有帮助：
> 
> 1. 能否将这个参数`-Dpowerjob.network.local.address`改成可以指定域名
> 2. 服务发现接口`DISCOVER_URL = "http://%s/server/acquire?appId=%d&currentServer=%s&protocal=AKKA"`中获取的地址能否改成可以手动配置，地址是指返回参数中的data`{"success": true,"data": "10.42.0.13:10086","message": null}`



> 你这个，server需要建立路由，通过设置域名xxxcom.cn访问容器，其次，在本地需要设置host做映射，127.0.0.1 xxxcom.cn，最后还要建立隧道，127.0.0.1 80----->容器的service ip 80。本地就可以通过域名xxxcom.cn访问server

**Comment by zltheone** [comment]
遇到了同样问题，本地worker服务需要调试，但是server返回的是pod的虚拟IP，又不能指定AKKA的IP，这怎么本地调试呢？

**Comment by git-aliuge** [comment]
网络是硬伤, K8S内部部署server和worker没问题, 本地IDEA启动的worker连接k8s的server没看到报错, 但是server控制台也看不到worker

**Comment by chaodongyue** [comment]
看了下源码, 根本原因是server调用worker是采用HTTP方式, worker作为服务端必须让server能通过http调用到, 那么就会牵扯到server调worker网络互通问题. 建议作者考虑一下把通讯协议换成长连接, 这样只要worker能连上server就行, 也能做到网络穿透.
