### ISSUE TITLE
[Feature]  脚本能否提供配置自定义运行成功

### ISSUE THREAD

**Issue by xjxjin** [KFCFans/PowerJob#28]
提供一种或多种选项，比如日志抛error，或者日志抛自定义内容，就可以判定日志执行情况，或者程序中断退出啥的判定任务执行成功或运行中或失败

**Comment by KFCFans** [comment]
已开发完成，现在会根据 shell 脚本执行完毕退出时的返回值判断。

the exit value of the subprocess represented by this {@code Process} object.  By convention, the value {@code 0} indicates normal termination.

将于下个版本发布。

**Comment by KFCFans** [comment]
since v3.2.1
