### ISSUE TITLE
[Feature] 新增帮助页面

### ISSUE THREAD

**Issue by xjxjin** [KFCFans/PowerJob#29]
提一个建议，在PowerJob 起个帮助之类的页面，放上你再github或者gitee的链接行不，有时候想进git不是很方便，文档里最好开头就把链接放上去

**Comment by KFCFans** [comment]
你是说 PowerJob 前端控制台吗？
那可是到处都是跳转链接啊……
首先是点击左上角的 PowerJob logo能跳转进 GitHub...
其次是控制台首页（显示机器列表的那一页）最上面第三个块就是文档地址和项目地址...
你去看看～

xjxjin <notifications@github.com>于2020年7月24日 周五下午8:45写道：

**Comment by KFCFans** [comment]
文档也是，首页的图片、蓝色的PowerJob和GitHub star数图标都能跳转进 GitHub

**Comment by xjxjin** [comment]
> 文档也是，首页的图片、蓝色的PowerJob和GitHub star数图标都能跳转进 GitHub

可能是我点的少，那文档里勒 可以添加下撒

**Comment by KFCFans** [comment]
感谢建议，可以的～
