### ISSUE TITLE
Can I cancel some of the tasks submitted with the same JobId? 

### ISSUE THREAD

**Issue by jjnnzb** [KFCFans/PowerJob#30]
**Is your feature request related to a problem? Please describe.**
I am doing a function just like the alarm clock. Users can randomly set alarm clocks, and cancel any of these clocks at ease. I found that with OpenAPI(runJob with delay time function), I can set these clocks, but cannot cancel them randomly.  Do I have to create distinct job for each alarm clock?

**Describe the solution you'd like**
I am wondering, if another API like `cancelTask(LocalDateTime runTime) `could be offered, and the runJob with delay time function could be `runJob(Long JobId, String jobParams,  LocalDateTime runTime)`.

**Describe alternatives you've considered**
Create different job with different jobId for each alarm clock.

**Additional context**
PowerJob is a good project, come on!

**Comment by jjnnzb** [comment]
I am sorry, it should be `cancelTask(Long JobId, LocalDateTime runTime)`.

**Comment by jjnnzb** [comment]
Or can I get a taskId when I run the `runJob(Long jobId, String instanceParams, Long delay)` function and the cancel task function is like cancelTask(Long jobId, Long taskId)?

**Comment by KFCFans** [comment]
cancelInstance(Long instanceId)

**Comment by KFCFans** [comment]
runJob 的时间参数用延迟毫秒数还是具体时间无非是你写代码还是我写代码的问题，这个不考虑修改 API。
一般来讲，老接口主要考虑兼容性，是不会去做改动的。

**Comment by KFCFans** [comment]
这个 feature 我开发的差不多了，提前说明一点：
这个接口使用有一点小小的限制：
**调用接口时间与待取消任务的预计执行时间要有一定时间间隔（至少 10 ms），否则不保证可靠性！**

原因如下：
调用该接口时间和预计调度时间相近时，理论上会出现问题，cancel 状态还没写进去另一边就完成了 dispatch，随后状态会被覆盖为 running，相当于 cancel 失败。解决该问题的成本极高（分布式锁），因此选择不解决

**Comment by KFCFans** [comment]
since v3.2.1

**Comment by jjnnzb** [comment]
Many thanks!
