### ISSUE TITLE
AppName任务查看

### ISSUE THREAD

**Issue by lius1010** [KFCFans/PowerJob#33]
后台是微服务化，多个服务 引用了  powerjob-worker  ，然后 AppName 是相同的。 
    想区分业务，job 上面能不能分组。 
    不想切换 不同的AppName ， 这样运维也有维护成功，要知道任务属于哪个 AppName。
   或是 用  多个 AppName 也行， 有一个超管看到所有的任务~

**Comment by KFCFans** [comment]
会提供一个全局 appName 的接口
可能会提供一个方便运维进入的界面

**Comment by KFCFans** [comment]
突然发现这个接口目前就有：
/appInfo/list
不过目前的限制是最多返回 50 条数据，下个版本放宽到 200。
如果超过这个数量，就自己写接口读 DB 吧...
