### ISSUE TITLE
【编辑】预警配置，返显错误

### ISSUE THREAD

**Issue by lius1010** [KFCFans/PowerJob#34]
使用  v3.2.1分支版本， 运行  powerjob-server  ，使用项目自带的前端界面，
    任务管理菜单，针对某一任务 进行编辑
    第一次点击 【编辑】添加 预警配置  成功之后
   第二次在点击【编辑】 在反显错误
![add](https://user-images.githubusercontent.com/9639445/88648256-66e5ed00-d0f9-11ea-997f-2c70eb323d8a.png)
![show](https://user-images.githubusercontent.com/9639445/88648290-706f5500-d0f9-11ea-9a78-9117ee9c05d0.png)

**Comment by KFCFans** [comment]
理论上应该是 element-ui  的 bug，我也尝试 fix 过，但无效......
