### ISSUE TITLE
日志查看查看优化

### ISSUE THREAD

**Issue by lius1010** [KFCFans/PowerJob#35]
希望 在某一任务后面 增加 【日志】按钮，只查看这个任务的日志信息。 
![菜单](https://user-images.githubusercontent.com/9639445/88649112-2dfa4800-d0fa-11ea-90e0-df8158b31be1.png)

**Comment by KFCFans** [comment]
预计下个版本支持

**Comment by KFCFans** [comment]
![image](https://user-images.githubusercontent.com/9402086/89128988-14a73080-d52c-11ea-9329-04a13e89c931.png)

since v3.2.2
