### ISSUE TITLE
stopInstance Asyn task

### ISSUE THREAD

**Issue by slyang520** [KFCFans/PowerJob#37]
**Is your feature request related to a problem? Please describe.**
Sync Job , can't get the right stop

In the following cases:

```java
@Override
public ProcessResult process(TaskContext context) throws Exception {
    performSync();
    where(true){
       // get staute,  ten seconds every time
       String result = fetchResult()
       if (result = "success" or "fail"){
           break;
       }else{
           Thread.sleep(1000*10)
       }    
    } 
    return ProcessResult.xxx ;
}

```

**Describe the solution you'd like**

expect:

Add the hook , to stop 

```java
TaskContext
    - stopInstanceHook

```

**Comment by KFCFans** [comment]
你好，我测试了一下，stop的功能是没问题的，见下图：
![image](https://user-images.githubusercontent.com/9402086/88917288-1b1e7980-d29a-11ea-817d-6b1ea9098710.png)

首先，Stop不是一个保证可靠的方法，如果发现任务仍在 running，可以再次 Stop。
其次，Stop 任务的前提条件是该任务能被 stop，也就是需要有能被打断的点，比如 Thread.sleep，如果线程一直占用 CPU 执行，Java并没有提供 API 来终止该线程。
最后，如果还有问题的，欢迎继续反馈。顺便带上你的操作系统信息、Java版本、PowerJob版本等信息。

**Comment by slyang520** [comment]
类似与SchedulerX2 的
public void kill(JobContext context)
https://help.aliyun.com/document_detail/148193.html
因为停止是否成功和业务有关。

**Comment by KFCFans** [comment]
也就是增加一个回调接口，让你自己处理 kill 逻辑吧。
说实话框架设计阶段我考虑过这个方案，但是先不到具体的业务应用场景，能麻烦你举个例子吗？
如果有合适的业务场景，我会在下个版本支持的。

**Comment by slyang520** [comment]
> 也就是增加一个回调接口，让你自己处理 kill 逻辑吧。
> 说实话框架设计阶段我考虑过这个方案，但是先不到具体的业务应用场景，能麻烦你举个例子吗？
> 如果有合适的业务场景，我会在下个版本支持的。

1L 那个就是很常见的场景。

**Comment by KFCFans** [comment]
不好意思，我其实没太看懂 1L 那个例子的意思 😂
代码在同步执行的时候，我提供给你调用 kill 接口的方法也无济于事啊......

其实我想问的是：
**什么情况下需要主动结束任务**，我认为的 stopInstance 是用在机器过载情况下手动停止某些任务实例的方法，所以只是一个单纯打断的操作。在我这种理解下，stopInstance 的实现也就是简单的打断线程。
而根据你的描述，似乎是把 stopInstance 作为了一个比较常规的业务操作，我很想知道是什么样的场景下需要使用 stopInstance。

**Comment by slyang520** [comment]
![image](https://user-images.githubusercontent.com/8638524/89275026-4cb98b00-d674-11ea-95a8-5f7c8cff9e35.png)

阿里云的kill示例 嘻嘻

**Comment by KFCFans** [comment]
所以说，这个示例只是为了演示而演示的。
如果 kill 的意义是让任务停止，我直接 stop 线程不是一样能到达效果吗？
**我需要的是真实有意义的且目前我这种 stop 机制无法支持的业务场景。**
如果没有，那其实就是没有必要的需求。

**Comment by KFCFans** [comment]
这个例子的 stop 判断完全可以换成 Thread.interrupted()，我的 stop 一样能达到目的。

**Comment by truelovesuju** [comment]
例如shell任务，子进程kill不掉
