### ISSUE TITLE
PowerJob server部署在k8s上，worker获取的是容器内ip+port

### ISSUE THREAD

**Issue by dudiao** [KFCFans/PowerJob#39]
**Describe the bug**
PowerJob server部署在k8s上，以ip+port或者域名的形式，暴露出来，提供服务。worker部署在非k8s环境中，这样worker获取到的server地址是k8s集群内的，造成通信故障。

**Environment**
 - PowerJob Version: [3.2.1]
 - server Java Version: [8-jdk-hotspot]
 - worker OS: [Windows10]

**Screenshots**
![Snipaste_2020-07-30_22-07-48](https://user-images.githubusercontent.com/38355949/88932792-1fa25c80-d2b1-11ea-815e-e7db5ee3a2f6.png)

![image](https://user-images.githubusercontent.com/38355949/88933371-e4545d80-d2b1-11ea-8be6-a393018015e3.png)

**Comment by dudiao** [comment]
1. 这里有个解决方案，但是需要server和worker能设置外部通信的IP和端口地址。
https://qingye.info/2020/03/29/k8s/k8s-dubbo/

2. spring cloud多网卡选择实现：https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/main/java/org/springframework/cloud/commons/util/InetUtils.java

**Comment by KFCFans** [comment]
该问题已被讨论过，见 issue：https://github.com/KFCFans/PowerJob/issues/27
worker 是不可能单独设置外部通信的 IP 的，比如，集群部署的时候怎么设置呢？

目前 PowerJob 的系统运行要求就是要求所有组件在同一个局域网中，不满足条件则无法运行。
