### ISSUE TITLE
Deploy multiple power workers on the same machine.

### ISSUE THREAD

**Issue by jjnnzb** [KFCFans/PowerJob#40]
**Is your feature request related to a problem? Please describe.**

```
 public class OmsWorkerFileUtils {

    private static final String USER_HOME = System.getProperty("user.home", "powerjob");
    private static final String WORKER_DIR = USER_HOME + "/powerjob/";

    public static String getScriptDir() {
        return WORKER_DIR + "script/";
    }

    public static String getContainerDir() {
        return WORKER_DIR + "container/";
    }

    public static String getH2Dir() {
        return WORKER_DIR + "h2/";
    }
}
```

The working directory of the project is set to `${user.home}/powerjob/h2`，and the database file name is always powerjob_worker_db.mv.db. So I am wondering if I deploy multiple workers for different works on the same machine, would any conflicts occur?

**Describe the solution you'd like**
Powerjob worker automatically reads _spring.application.name_ from application.properties?

**Describe alternatives you've considered**
Generate different paths for different projects, or read path from application.properties, or set different names for different databases?

**Additional context**
Many thanks!

**Comment by KFCFans** [comment]
通过接入的应用名来隔离运行时文件是一个非常好的 idea！
下个版本 worker 的工作路径会改成 `~/powerjob/$appName/UUID/powerjob/h2`
感谢支持，敬请期待～
（预计本周末发布新版本

**Comment by dudiao** [comment]
UUID改成port是不是更好点： `~/powerjob/$appName/port/powerjob/h2`

**Comment by KFCFans** [comment]
since v3.2.2
