### ISSUE TITLE
是否支持常驻任务

### ISSUE THREAD

**Issue by zywj** [KFCFans/PowerJob#42]
比如队列的消费者之类的任务

**Comment by KFCFans** [comment]
目前的秒级任务（固定频率和固定延迟）就是常驻任务，比如固定延迟就是每 10s 执行一次任务，最低的运行频率为 1S 一次，不知道是否符合你的需求。
![image](https://user-images.githubusercontent.com/9402086/89115909-729e2e80-d4c0-11ea-84bd-88a17a752fc9.png)

**Comment by zywj** [comment]
谢谢这么快速的回复。可能我的这个需求用法就不对。不应该用在任务调度框架上。
