### ISSUE TITLE
关于用户登录与鉴权事宜

### ISSUE THREAD

**Issue by nvkou** [KFCFans/PowerJob#43]
# 用户登录接口与权限

## feature场景与主要矛盾
- powerJob虽然有分布式，但同一个公司不见得会为不同工作组建立不同的server实例来追踪记录
- 许多公司有内部的身份系统，单独为powerjob-server做简单的用户登录鉴权是重复造轮子
- 也有许多公司没有内部身份系统，但希望有用户隔离

## 提出的方案
 添加Spring Security+Keycloak 服务器的可选发布版本  keycloak参考简介 https://zh.wikipedia.org/wiki/Keycloak

选用keycloak是因为我们自己在使用，可能不是最佳解决方案，但对比自己造轮子。有以下优势
- 开箱即用
- 红帽出品，版本迭代稳定
- 支持OpenID connect 2.0 和SAML协议。均为业界标准协议，轮子多
- 可作为broker整合企业LDAP（active dictionary之类的）
- 内置多个平台的OAuth接口，配置即可用
- kerberos双向认证

选用这个方案，既可以让keycloak自行管理用户，也可以继承企业自己的身份提供。
举例 https://www.keycloak.org/2017/03/how-to-setup-ms-ad-fs-30-as-brokered-identity-provider-in-keycloak.html

## 我自己已测试的点
- powerjob-server 添加spring security，keycloak starter，链接测试keycloak服务器
- rest控制器添加基于role的鉴权

### 测试结果
- spring security成功拦截非鉴权请求
- vue前端显示unauthorized

## 需要做的事情
- vue添加keycloak  参考 https://medium.com/keycloak/secure-vue-js-app-with-keycloak-94814181e344
- 向后端索取keycloak配置以初始化前端keycloak
- 向后端发起请求时带上token

# 需要确定的事情
- 如果引入用户的概念，其用户的用例需要讨论
- 如果引入权限的概念，其权限组的用例需要讨论
- 当前登录与鉴权只在mvc框架内，未覆盖akka部分
- 重写landing页面，根据角色或所有者展示app状态，app名+密码没有必要

群友 {NK}

**Comment by KFCFans** [comment]
PowerJob 在用户和权限这一块上，永远只有一种方式，那就是扩展。也就是 powerjob-server 本身开箱即用的情况下，没有用户登陆和鉴权的概念。

在我理想的设计中，powerjob-server 不应该集成任何一个鉴权或者 SSO 框架，这些都是需要用户自己接入的。PowerJob 需要的是提供扩展点，比如一组接口。用户如果有相应的 SSO 或者权限需求，那就自己去实现相关的方法，对接需要的框架。

我目前的想法是用户实现自己的 HandlerInterceptorAdapter，然后从请求中拿到自己想要的信息（一般来说其实就是操作者 operator），之后就可以进行拦截判断了。同时，通过拦截器拿到操作人信息后，Job、Workflow 的操作记录也就解决了。

**Comment by nvkou** [comment]
我理解你的观点，我以前也是这么想的。但现实情况是用户自有的权限系统是多样化的，也不一定是java。如果重复暴露通用接口也只是复读一遍openID/SAML. 

引入一个服务端（身份broker），服务端对server是固定的权限系统。服务端再直接与外部身份系统对接既保留了灵活度（编程语言不相关，协议不相关。配置就行了），也降低了维护难度（server只对接一个身份broker）。
比如说。 
``` java
@RequestMapping("/foo")
@PreAuthorize("hasRole'jobAdmin' OR hasRole'superAdmin'")
public JSONObject bar(){...}
```
在代码层面就很容易做到鉴权，但是jobAdmin这个角色名称却不是通用约定，最终还是转嫁到开发者身上。使用身份broker的话，可以很容易的做再mapping   ‘GroupLeader’ -> 'jobAdmin'。配置就完成的事，干嘛还要开发呢


我提出来只是单纯因为我们需要集成登录鉴权，就跟你的设想一样。我们选择了某一种实现，只是个人觉得这个实现也有可能成为一个通用方案。

如果powerjob像fastjson一样定位成一个工具包到也不是问题。但我觉得应该向activity看齐 https://activiti.gitbook.io/activiti-7-developers-guide/getting-started/getting-started-activiti-cloud

**Comment by KFCFans** [comment]
中间件最重要的一点就是最小依赖。
每多一个外部依赖，用户接入的成本就会高很多。像我用了一个可选的 MongoDB 都有许多人希望完全去除，因为他们的公司没有这个技术栈。所以基于这一点，我觉得引入独立的鉴权服务器对我来说成本太高了。

keycloak 也许是通用方案，但不是适合 PowerJob 的方案。

**Comment by KFCFans** [comment]
我觉得我的想法和你的想法并不冲突啊。
你自己用独立的鉴权服务器，让请求中携带某些信息。然后在 powerjob-server 的前置拦截器中获取这些信息进行判断就行了。

我看我们公司的解决方案就是这样的，可以直接从 HttpServetRequest 中获取用户的信息，然后自己做判断就行了。开发量也很小，实现一个 Interceptor 就行。

**Comment by nvkou** [comment]
明白了。不是一个广泛需求

**Comment by KFCFans** [comment]
其实这算是一个广泛需求，比如 Gitee 上很早就有人提 [issue](https://gitee.com/KFCFans/PowerJob/issues/I1OMQK) 问过相关的问题，QQ 群里也时不时有人问权限和登陆的事。
只是我目前还没有探索出我认为合理且完美的方案。因为我其实也并没有怎么接触过 SSO 和鉴权这类框架，这方面不是很熟，导致这一块也有点难产。
说白了我现在处于一个能否定别人方案但是自己却拿不出方案的阶段，很尴尬......但我觉得我的否定应该是正确的，毕竟对于需要部署的大型框架，外部依赖真的非常需要注重的点。本着最小依赖的原则，我无法容忍 powerjob-server 去连接一个鉴权服务器。
而且 powerjob-server 本身也就是一个普通的 SpringBoot 应用，我认为接入方如果要大规模接入使用的话，花一点点时间进行权限改造也并不是什么高成本的事情。毕竟说白了鉴权代码甚至能直接从其他系统拷过来。

综上所述，目前无法支持，非常抱歉。
