### ISSUE TITLE
接入钉钉群告警 Integrate with DingTalk

### ISSUE THREAD

**Issue by jjnnzb** [KFCFans/PowerJob#45]
**Is your feature request related to a problem? Please describe.**
任务执行失败，可否接入钉钉群告警？
Would there be DingTalk alarm messages sent when the task execution failed?

**Additional context**
短信告警耗费资源，没必要。邮箱告警也不是很实用。能否接入钉钉这种工作级的工具呢？如果能接入，最好不过了。
It is expensive and annoying to send messages when the task execution failed, so is sending alarms via emails. It would be more friendly to support DingTalk for messaging.

**Comment by KFCFans** [comment]
https://ding-doc.dingtalk.com/doc?spm=a311a.9588098.0.0#/serverapi2/pgoxpy
预计使用该方案，需要自行创建企业内部应用。
