### ISSUE TITLE
没有和Elastic-Job的对比？

### ISSUE THREAD

**Issue by runshinex** [KFCFans/PowerJob#47]
为什么有和QuartZ的对比（主要使用场景不同），却没有和Elastic-Job的对比？
Elastic-Job目前应该是同类产品在国内使用最广泛的吧...强烈建议跟Elastic-Job做下对比。

**Comment by KFCFans** [comment]
elastic-job 前段时间都不维护了，最近才重新开始维护。
后期补上吧……


runshinex <notifications@github.com>于2020年8月7日 周五下午1:05写道：

**Comment by KFCFans** [comment]
ElasticJob-Lite 本质上可以理解为 QuartZ 的强化版，引一个 Jar 包，然后服务一个工程。和 PowerJob 不属于一个维度的东西，PowerJob 提供的是中间件式解决方案，服务的范围是整个公司所有业务线所有有调度需求的系统。从这一点来看，PowerJob 对标的应该是 ElasticJob-Cloud。

ElasticJob-Cloud 似乎没有前端界面（这样就不支持在线的任务运维、监控和日志查看），支持的任务类型也很少（似乎没有广播执行，肯定没有动态分片和分布式计算），定时策略好像也比较单一（这个不确定），也不支持工作流 workflow（参考如下）......要我评价的话，就是阉割版的 PowerJob......

![image](https://user-images.githubusercontent.com/9402086/89737312-8b02e000-daa2-11ea-8e73-9bbb91afe81d.png)

而且文档我看了一遍还是稀里糊涂的......
综上，强烈推荐使用 PowerJob～
