### ISSUE TITLE
是否可以配置未来某一个时间点执行任务？

### ISSUE THREAD

**Issue by amsz** [KFCFans/PowerJob#50]
需求是在未来的一个时间点，任务只需执行一次，这种情况CRON好像无法实现。

**Comment by telami** [comment]
1 12 14 20 5 2021

corn不是可以嘛

**Comment by amsz** [comment]
好的，谢谢了

**Comment by KFCFans** [comment]
同时，任何自定义的调度需求，都可以通过 OpenAPI 来实现。
