### ISSUE TITLE
基于Powjob扩展脚本任务功能

### ISSUE THREAD

**Issue by xiaoxia0617** [KFCFans/PowerJob#51]
**我现在的需求是: 创建的流程任务可以支持编辑时定义任务节点的配置信息(PowerJob原生是只支持导入事先创建好的任务节点作为流程中的步骤节点来编排任务)**
     a. 这里我的前端会替换现有的DAG编辑器, 编辑器支持拖拽任务节点, 允许配置任务节点数据
     b. 我想扩展job实体结构, 增加新的processor, 主要是为了支持ansible playbook脚本的分发和执行
     b. 鉴于我想基于powerjob开发, 可否专门创建一个分支供我来提交满足我需求的功能代码?
     c. 我怎样加入到项目里来贡献代码?

**Comment by KFCFans** [comment]
关于贡献，就是传统的流程，先开个 Feature 描述下你准备做的事情，然后 fork 项目，基于 master 进行开发，开发并测试完成后提交 PR，如果我觉得没问题就会合并到主干，你也就成为正式的贡献者了。

前端方面的改动基本没什么限制，你要是想丰富功能的话直接按上诉流程操作就行。

关于 PowerJob 的改动一定要提前开 Feature 描述清楚（用这个帖子也行，看你自己），经过讨论和评估确定方案后再动工，具体可以参考： 
#19 这个 Feature，在共同的讨论下，最后成功落地
#43 这个 Feature，经过讨论发现没有普适性，因此放弃

最后，增加 Processor 是一件非常严肃的事情。这种底层的 API，一定要有非常普适的场景。希望你能把需求场景描述清晰，让我们共同寻求一个合理的解决方案。

感谢～
