### ISSUE TITLE
建议worker可以指定自己的ip

### ISSUE THREAD

**Issue by JackyLeeCS** [KFCFans/PowerJob#53]
现在server和worker只能在同一个局域网中，限制太大。建议worker可以通过配置的方式指定自己的ip和端口，达到与server通讯的目的。

**Comment by KFCFans** [comment]
server 和 worker 是需要双向通讯的，所以必须在一个局域网内。
配置 IP 是小孩子过家家行为，你集群部署的时候怎么配置 IP？
别用看待 RPC 框架的角度来看待中间件。
