### ISSUE TITLE
scala/Product$class

### ISSUE THREAD

**Issue by administrator319** [KFCFans/PowerJob#54]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initPowerJob' defined in class path resource [com/github/kfcfans/powerjob/worker/autoconfigure/PowerJobAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: scala/Product$class

**Comment by KFCFans** [comment]
这个就是典型的依赖冲突了，你的项目本身是不是就有 Scala 依赖？

**Comment by KFCFans** [comment]
排包指南
https://www.yuque.com/powerjob/guidence/xp5ygc#GCYg1
