### ISSUE TITLE
cancel dispatch job due to no worker available, clusterStatus is CAN'T_FIND_ANY_WORKER

### ISSUE THREAD

**Issue by javaXiaoHan** [KFCFans/PowerJob#55]
根据官方文档demo已经跑起来了。然后在自己的springMVC项目里面配置了OhMySchedulerConfig和BasicProcessor 
然后就提示can't find any worker for app(appId=2) yet. 日志里面也是no worker available
![1](https://user-images.githubusercontent.com/32090060/90314258-f33f3f00-df44-11ea-9e49-226d2d4cd80a.png)
![2](https://user-images.githubusercontent.com/32090060/90314264-f76b5c80-df44-11ea-8c87-1d8c06c96fa2.png)

**Comment by javaXiaoHan** [comment]
这个是在demo的基础上  在自己的spring项目里面加了一个任务

**Comment by KFCFans** [comment]
需要先去前端控制台注册你的 appName。
读文档永远是最好的问题解决方式。

javaXiaoHan <notifications@github.com>于2020年8月15日 周六下午10:23写道：

**Comment by KFCFans** [comment]
我好像理解错意思了......
worker 和 server 是处于同一个局域网内吗？如果不是在同一个局域网内，PowerJob 是无法正常工作的。
原因见常见问题：https://www.yuque.com/powerjob/guidence/xp5ygc#xMQC9

**Comment by KFCFans** [comment]
如果不是网络问题，请把 server 和 worker 的日志文件贴上来。同时提供 PowerJob 、JVM、操作系统的版本信息。

**Comment by javaXiaoHan** [comment]
> 如果不是网络问题，请把 server 和 worker 的日志文件贴上来。同时提供 PowerJob 、JVM、操作系统的版本信息。
1：appName 已注册
2：项目是在在一个笔记本电脑上跑起来的。
3：java8，win10系统，powerjob-worker版本是3.2.2
        <artifactId>powerjob</artifactId>
        <groupId>com.github.kfcfans</groupId>
        <version>2.0.0</version>
![1](https://user-images.githubusercontent.com/32090060/90334322-7624d000-dfff-11ea-9c45-ecf6c63a654a.png)
![2](https://user-images.githubusercontent.com/32090060/90334324-77ee9380-dfff-11ea-99ca-b5b7680d5075.png)
![3](https://user-images.githubusercontent.com/32090060/90334325-7ae98400-dfff-11ea-8e36-19071df7beae.png)

**Comment by KFCFans** [comment]
哈哈哈哈哈，你就不会找一下不同吗......
你和 demo 程序最大的不同，就是版本呀。
3.2.2 存在着一个小 bug，当本地磁盘大于 1TB 是服务会不可用......升级到最新版 3.2.3 就好了。
![image](https://user-images.githubusercontent.com/9402086/90334492-91440f80-e000-11ea-8fcf-4165f38d3e8f.png)
