### ISSUE TITLE
工作流启动时候是否可以增加参数

### ISSUE THREAD

**Issue by yngjea** [KFCFans/PowerJob#58]
在使用OPENAPI启动单个任务时候，是有输入参数instanceParams，但是在工作流启动的时候，只能使用一个工作流id进行启动，而没有instanceParams，是否可以增加instanceParams在启动时候接收到对应的任务参数，谢谢

**Comment by KFCFans** [comment]
考虑支持，敬请期待

**Comment by MasonCai** [comment]
@KFCFans  同需这个功能，请问这个功能10月份能上线吗？

**Comment by KFCFans** [comment]
> @KFCFans 同需这个功能，请问这个功能10月份能上线吗？

国庆结束发布。
都有需求了，去填个接入登记咋样？

**Comment by KFCFans** [comment]
已正式发布。
希望各位接入生产环境使用的亲能动动小手填写一下接入登记：https://github.com/KFCFans/PowerJob/issues/6
