### ISSUE TITLE
网络分区的情况

### ISSUE THREAD

**Issue by why2012** [KFCFans/PowerJob#59]
### 目前缺乏节点嗅探机制，Worker实例只会访问启动时配置的server地址，且server端主节点选举依赖于Worker触发，因此不利于动态添加server节点。添加server节点后，需要重启Worker实例，才能使其生效。
 ### 此外，若出现网络分区，可能会出现server端主节点切换，导致Worker数据上报的server不一致的现象，server端调度时也无法获取所有可用Worker。worker1与worker2在这种情况下不会被调度到。

server1(last leader)            |                 server2(new leader)
      |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;partition &nbsp;&nbsp;&nbsp; |
      | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      \ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      |
worker1  worker2       &nbsp;&nbsp;&nbsp;|          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       worker3

**Comment by KFCFans** [comment]
# 关于节点嗅探机制
1. 在不依赖 zookeeper 的情况下，动态发现 worker 是不可能的事情。毕竟追求动态上线的话，肯定要去某个地方读取可用的服务信息，比如作为注册中心的 zookeeper。
2. powerjob-server 的调度性能非常强，一般生产环境部署 2 ～ 3 台机器组个高可用就行了。单从性能的角度来讲，我觉得你甚至很难填满一台 server。大概率性能瓶颈会出现在 DB 上。
3. 动态嗅探其实也是可以实现用，用域名就行。powerjob-worker的配置是支持域名的，而域名到 IP 这个解析是有动态能力的。

# 关于脑裂（网络分区）
* 你至始至终忽略了第三者的存在，也就是 DB。除非你的 DB 也支持多机房双写，否则一旦网络分区，连不到 DB 的那台 server 是无法正常工作的。
* 假如你的 DB 也支持多机房双写，那么一旦网络分组，其实两个分组各自的 server 和 worker 组成独立集群，任务仍然会正常调度和执行（因为 DB 也被隔离了，所以数据无法同步）

**Comment by why2012** [comment]
- 假如出现server1和server2分区，但是两个server都能访问db的情况呢
- 域名需要SLB服务支持，akka用的应该是长连接，如果server1宕掉，所有worker都会连server2，worker很多的情况下，有可能出问题，这时把server3加进来，除非server2也宕掉，否则worker请求不会被自动均衡到server3，除非SLB服务支持动态切换长连接
- server_info表存的应该是所有可用server吧，可否发一份给worker
- 目前的设计，在服务发现后，所有worker在都会连leader server，其他server作为备份，在worker数量很多的情况下，是否会是一个瓶颈，用域名能解决这个问题，但同时会出现第二点提到的server越来越少，最终worker请求也会集中到同一个server的问题

**Comment by KFCFans** [comment]
1. 太奇葩，不考虑。而且这种情况下 DB 主从之间其实也已经断连了，情况太复杂，没意义了......
2. 负载均衡其实不用太在意。powerjob-server 拥有极强的单机调度性能，细微的偏斜其实影响不大。
3. 我觉得目前的服务发现机制挺完美的，虽然确实会有理论上的偏斜等问题，但实际情况下都不是问题。
4. 这个问题其实还是 akka 是长连接还是断连接的问题。如果是短连接就没有负载问题了。如果不是，那么这个我后续可以优化为短连接来解决这个问题，毕竟 worker 每隔 15S 才发送一次心跳到 server，长连接意义不大。
