### ISSUE TITLE
powerjob-server模块打包发布到maven中央仓库

### ISSUE THREAD

**Issue by xiaoxia0617** [KFCFans/PowerJob#61]
**Is your feature request related to a problem? Please describe.**
我想使用powerjob-server中流程管理、实例管理、流程引擎处理这块的功能, 但不想把powerjob-server中的代码完整的复制到自己的工程中; 希望能直接通过依赖powerjob-server这个包, 将其核心功能引入本项目, 好处是自己可以扩展流程管理功能提供符合自己业务的REST API；另外, 可以做一个类似powerjob-worker-spring-boot-starter一样的powerjob-server-spring-boot-starter模块
-
**Describe the solution you'd like**

**Describe alternatives you've considered**
将powerjob-server发布到maven中央仓库 或者 增加一个powerjob-server-spring-boot-starter层

**Comment by KFCFans** [comment]
其实在我一开始的设想中，powerjob-server 就应该是一个独立的 jar，负责调度和任务的管理。但是后面发现难以划分边界，重新思考后我认为目前这种模式就是合理的。
毕竟 PowerJob 的定位是中间件，需要统一、集中部署 server 是一件非常正常的事情。至于你想要的扩张功能，你可以选择在 powerjob-client（OpenAPI）的基础上进行二次开发。
非常不建议拷代码......部署 server 用 OpenAPI 扩展才是正确的打开方式。

**Comment by dudiao** [comment]
如果powerjob-client和powerjob-server在同一个项目（JVM）里，是不是既能满足扩展，又没有拷代码

**Comment by KFCFans** [comment]
> 如果powerjob-client和powerjob-server在同一个项目（JVM）里，是不是既能满足扩展，又没有拷代码

他就是不想单独部署 server，想直接拿一部分能力集成到已有系统中，这个不考虑支持。
