### ISSUE TITLE
client-3.2.0和worker-3.2.3冲突

### ISSUE THREAD

**Issue by ALittleBrother** [KFCFans/PowerJob#62]
文档里给出的依赖版本client-3.2.0和worker-3.2.3冲突，会导致项目启动失败，都用3.2.3的话可以正常启动，希望大佬有空更新下文档哦~~
![TIM图片20200828145724](https://user-images.githubusercontent.com/38495823/91531102-cf193000-e93e-11ea-9c54-58485489a9ce.png)

**Comment by KFCFans** [comment]
感谢建议～会的～
