### ISSUE TITLE
源码部署时power-server启动卡住

### ISSUE THREAD

**Issue by StevenKin** [KFCFans/PowerJob#65]
## Question

[root@VM_0_16_centos` target]# java -jar powerjob-server-3.2.3.jar --spring.profiles.active=product

12:34:42.761 [main] INFO com.github.kfcfans.powerjob.server.OhMyApplication -

******************* PowerJob Tips *******************
如果应用无法启动，我们建议您仔细阅读以下文档来解决:
if server can't startup, we recommend that you read the documentation to find a solution:
https://www.yuque.com/powerjob/guidence/xp5ygc#xMQC9
******************* PowerJob Tips *******************

12:34:42.848 [main] INFO com.github.kfcfans.powerjob.server.akka.OhMyServer - [OhMyServer] OhMyServer's akka system start to bootstrap...
12:34:42.937 [main] INFO com.github.kfcfans.powerjob.server.akka.OhMyServer - [OhMyWorker] akka-remote server address: 172.17.0.16:10086
12:34:46.470 [oms-server-akka.actor.default-dispatcher-6] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
12:34:47.027 [oms-server-akka.actor.default-dispatcher-6] WARN akka.remote.RemoteActorRefProvider - Using the 'remote' ActorRefProvider directly, which is a low-level layer. For most use cases, the 'cluster' abstraction on top of remoting is more suitable instead.
12:34:47.028 [oms-server-akka.actor.default-dispatcher-6] WARN akka.remote.RemoteActorRefProvider - Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
12:34:49.152 [main] INFO com.github.kfcfans.powerjob.server.akka.OhMyServer - [OhMyServer] OhMyServer's akka system start successfully, using time 6.304 s.
12:34:49.423 [main] INFO org.springframework.core.KotlinDetector - Kotlin reflection implementation not found at runtime, related features won't be available.

日志就显示到这里然后就卡住了

**Comment by KFCFans** [comment]
这不是卡住，是后面的信息打到日志文件里了……
