### ISSUE TITLE
是否支持 指定任务的开始时间和结束时间

### ISSUE THREAD

**Issue by TuChenH** [KFCFans/PowerJob#67]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details. 

想请问一下 是否支持选择任务的开始时间和任务的结束时间.

**Comment by KFCFans** [comment]
暂时不支持，只能通过 OpenAPI 自行实现，不过我觉得这是一个可以支持的特性。
在下个版本应该会考虑支持，敬请期待。
PS：下个版本预计国庆后发布

**Comment by TuChenH** [comment]
> 暂时不支持，只能通过 OpenAPI 自行实现，不过我觉得这是一个可以支持的特性。
> 在下个版本应该会考虑支持，敬请期待。
> PS：下个版本预计国庆后发布

好的 谢谢!
