### ISSUE TITLE
是否可以考虑加上“初次延时”的功能

### ISSUE THREAD

**Issue by ALittleBrother** [KFCFans/PowerJob#68]
**当前功能.**
现在的固定频率和固定延时任务在新建后会立即执行一次，之后按照固定的频率继续执行

**业务需求**
需要指定第一次任务的执行时间

**功能建议**
能否考虑加上“初次延时”的功能，指定第一次任务的执行时间
类似spring的schedule
如：initialDelay = 1000, fixedRate = 3000     第一次任务在创建后1s执行，之后3s执行一次

**Comment by wnjustdoit** [comment]
你这要的是 固定延迟 + 固定频率 的组合功能呀。

**Comment by ALittleBrother** [comment]
> **当前功能.**
> 现在的固定频率和固定延时任务在新建后会立即执行一次，之后按照固定的频率继续执行
> 
> **业务需求**
> 需要指定第一次任务的执行时间
> 
> **功能建议**
> 能否考虑加上“初次延时”的功能，指定第一次任务的执行时间
> 类似spring的schedule
> 如：initialDelay = 1000, fixedRate = 3000 第一次任务在创建后1s执行，之后3s执行一次

**Comment by KFCFans** [comment]
任何自定义调度需求自行通过 OpenAPI 扩展实现。
