### ISSUE TITLE
已删除的任务仍可点击重跑继续执行

### ISSUE THREAD

**Issue by ALittleBrother** [KFCFans/PowerJob#69]
**Describe the bug**
  如题

**To Reproduce**
- 新建任务，任务正常执行
- 删除任务，相关实例停止运行
- 点击重跑，已删除的任务又可继续运行

**Expected behavior**
用户在尝试执行已删除任务时应提醒用户“该任务已删除”并停止启动该任务

**Environment**
 - PowerJob Version: 3.2.3
 - Java Version: OpenJDK 8
 - OS: CentOS 7

**Comment by KFCFans** [comment]
正常设计，无负面影响，忽略。
