### ISSUE TITLE
基于源代码编译后无法运行

### ISSUE THREAD

**Issue by Link-Kou** [KFCFans/PowerJob#70]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'localEntityManagerFactory' defined in class path resource [com/github/kfcfans/powerjob/server/persistence/config/LocalJpaConfig.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

**Comment by KFCFans** [comment]
依赖问题，文档和百度都能解决。
