### ISSUE TITLE
open API 调用saveJob方法，RequestBody.create(json, jsonType) 转换异常

### ISSUE THREAD

**Issue by chutianhua** [KFCFans/PowerJob#71]
open API 调用saveJob方法，RequestBody.create(json, jsonType) 转换异常
[](url)

**Comment by KFCFans** [comment]
问题描述不够全面，无任何辅助判断手段。

**Comment by xiaoshi1994** [comment]
我这边业报了同样得问题：
![~X1QBFPQD4N3OF53{A6W%{T](https://user-images.githubusercontent.com/31305740/95547040-a3589200-0a34-11eb-9ccd-a5bba2446387.png)
![K MU34A%YAB)S5W9R5T5VPG](https://user-images.githubusercontent.com/31305740/95547050-a81d4600-0a34-11eb-945b-f134b8bda558.png)
![0G2ZS@A~W2VWPRXDZP2GMLL](https://user-images.githubusercontent.com/31305740/95547057-ac496380-0a34-11eb-90b1-391e81e56241.png)
![P3YHM(59HCKQP0P0TQ )BT2](https://user-images.githubusercontent.com/31305740/95547062-afdcea80-0a34-11eb-87df-079d126a1d26.png)

**Comment by ylang2017** [comment]
@xiaoshi1994 我这边遇到过类似的问题，尝试一下把okhttp的包升级到4.4.1试试。
