### ISSUE TITLE
执行器启动错误

### ISSUE THREAD

**Issue by xieende** [KFCFans/PowerJob#75]
您好，执行器在启动的时候，不能正常启动

**Comment by xieende** [comment]
Description:

An attempt was made to call the method kotlin.collections.ArraysKt.copyInto([B[BIII)[B but it does not exist. Its class, kotlin.collections.ArraysKt, is available from the following locations:

    jar:file:/D:/m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.jar!/kotlin/collections/ArraysKt.class

It was loaded from the following location:

    file:/D:/m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of kotlin.collections.ArraysKt


Process finished with exit code 1

**Comment by KFCFans** [comment]
jar 包版本冲突，请自行排包解决。
mvn dependency:tree

**Comment by xieende** [comment]
感谢，但是有个更奇怪的问题，执行器启动了，然后app_name 也是server注册那个，
但是，在server 控制台没有执行器机器列表，使用的官网docker构建，
其中，使用咱们自带的例子也是这样，发现有一个10086端口连不上，这个端口是按照docker run 要求直接映射出来的。

[outbound connection to [akka://oms-server@172.17.0.2:10086], control stream] Upstream failed, cause: StreamTcpException: Tcp command [Connect(172.17.0.2:10086,None,List(),Some(5000 milliseconds),true)] failed because of akka.io.TcpOutgoingConnection$$anon$2: Connect timeout of Some(5000 milliseconds) expired
2020-09-27 11:23:17 WARN  - [outbound connection to [akka://oms-server@172.17.0.2:10086], message stream] Upstream failed, cause: StreamTcpException: Tcp command [Connect(172.17.0.2:10086,None,List(),Some(5000 milliseconds),true)] failed because of akka.io.TcpOutgoingConnection$$anon$2: Connect timeout of Some(5000 milliseconds) expired
2020-09-27 11:23:22 DEBUG - [OmsServerDiscovery] current server is 172.17.0.2:10086.
