### ISSUE TITLE
源码部署启动也不报错，但是没成功

### ISSUE THREAD

**Issue by xieende** [KFCFans/PowerJob#77]
![image](https://user-images.githubusercontent.com/7939079/94359571-cf8e1d80-00da-11eb-86d1-4876ceed5fc6.png)

![image](https://user-images.githubusercontent.com/7939079/94359577-d583fe80-00da-11eb-8511-abb90e6b9b8e.png)

**Comment by KFCFans** [comment]
分清楚标准输出 SOUT 和 日志文件的区别。
这只是启动初期打印到标准输出的内容，并不代表启动成功。
