### ISSUE TITLE
关于powerjob的可落地性疑问

### ISSUE THREAD

**Issue by JerryFoundation** [KFCFans/PowerJob#78]
你好，目前我们项目在进行分布式调度框架选型，之前使用的是当当的 elasticjob，由于很久没有维护，现在需要找一款替代， 现在在xxl-job和powerjob之间纠结，我个人看了一下powerjob还是挺偏爱这边， 请问powerjob的稳定性能否达到生产级别？ 有没有实际落地案例和参考数据。 诚盼回复

**Comment by KFCFans** [comment]
看下接入登记你就能明白可落地行有多强了。
希望你在接入以后也能回来填个登记。
https://github.com/KFCFans/PowerJob/issues/6
