### ISSUE TITLE
安装了虚拟机，执行器的27777监听不到

### ISSUE THREAD

**Issue by xieende** [KFCFans/PowerJob#80]
HI，
源码部署方式：
在执行机器装了虚拟机，然后启动worker的时候，27777的监听自动监听到了虚拟机的ipv4，只有将所有虚拟机都禁用，
才能监听本机的ipv4

**Comment by dudiao** [comment]
可以在worker启动时，添加 JVM 启动参数`-Dpowerjob.network.interface.preferred=xxx`来指定绑定的网卡（该参数需要填入需要绑定的网卡名称），或通过`-Dpowerjob.network.interface.ignored=xxx`来忽略错误的网卡（该参数支持增则表达式，匹配到的网卡会被忽略）。
