### ISSUE TITLE
脚本任务的脚本文件内容不支持换行

### ISSUE THREAD

**Issue by HoXianSen** [KFCFans/PowerJob#82]
**脚本任务的脚本文件内容不支持换行**
以python脚本为例：
写好脚本之后，在控制台的输入框复制脚本文件时会把换行符丢弃（input不支持换行符），导致worker生成文件格式有问题。
![image](https://user-images.githubusercontent.com/26298508/95995843-94bf1000-0e64-11eb-936b-c3ed96b26e00.png)

**Comment by KFCFans** [comment]
这种情况下，只能生成脚本的下载链接，然后填入下载地址了...
![image](https://user-images.githubusercontent.com/9402086/96330854-63745900-108b-11eb-9c45-09c7c3a404f6.png)

**Comment by KFCFans** [comment]
后续考虑 powerjob-server 支持简易的文件托管功能，方便脚本的管理。
