### ISSUE TITLE
docker部署powerjob能否将绑定ip与发布ip分开

### ISSUE THREAD

**Issue by MAOUXSAKI** [KFCFans/PowerJob#84]
#27 
#22 
我看了下，akka建立连接的机制应该是由发起端发起一个请求，然后接收端返回自己绑定的ip返回给发起端，然后双方建立连接。这个机制其实是和kafka是差不多的。
在这种情况下，在开发的时候，如果Powerjob-server部署在了kubernetes中，在开发端也就是自己的主机上连接kubernets中的Powerjob-server的时候，服务端就会返回kubernetes中的ip和端口，而这个ip和端口只有在kubernetes集群内才能连接。
所以这种情况下就需要将akka的绑定ip与发布ip分开。
事实上akka也确实存在host与bind-host的配置，但是我不知道在这个项目中是否可以使用，如果能使用是否会有什么问题，还请告知。

**Comment by MAOUXSAKI** [comment]
现在实验出一个曲线救国的方案
1. 首先更改源码使得可以通过配置环境变量更改绑定Hostname
2. 在容器启动的时候可以通步骤一的环境变量配置一个内部可以解析的域名
3. 将容器的主机名设置为该域名
4. worker启动连接
以上步骤是双方可以互连，但是不知道可能会有什么问题
该方案最多只能算是临时方案
是否能有更完全的一个方案

**Comment by KFCFans** [comment]
框架本身不会去支持非局域网运行的需求，这一点所有中间件都一样。

至于开发机连server这个问题，
1. 正常来说公司内至少有2套环境，一套日常开发用，一套正式生产环境。日常环境和办公网环境互通。那么直接在日常环境部署 server 集群即可。
2. 其他方式都可以用 VPN 解决，使用 -Dpowerjob.network 相关参数绑定到虚拟网卡即可（https://www.yuque.com/powerjob/guidence/xp5ygc#ZaRnE）
3. K8S 集群可以使用宿主网络，虽然我没实践过，但一定是有解决方案的，希望你自己好好摸索下。
