### ISSUE TITLE
修改应用名称时候的小问题

### ISSUE THREAD

**Issue by jjnnzb** [KFCFans/PowerJob#86]
**Describe the bug**
修改应用名称的时候，密码如果不填，就会被更新为null，且无法登陆进去。手动到数据库表里改密码才能成功进去。

**Environment**
 - PowerJob Version: 3.2.3
 - Java Version:OpenJDK 8
 - OS:CentOS 7

**Screenshots**
![Capture20201020163355.png](https://i.loli.net/2020/10/20/WHT4LJq91AcUtX3.png)

**Comment by KFCFans** [comment]
哈哈，有兴趣可以提个 PR 修复下～

**Comment by jjnnzb** [comment]
> 哈哈，有兴趣可以提个 PR 修复下～

哈哈哈，好的
