### ISSUE TITLE
文档中3.3.1版本的client jar引入到项目中出现无法启动的情况

### ISSUE THREAD

**Issue by anxinyh** [KFCFans/PowerJob#88]
源码部署server
在项目中同时引入powerjob-client和powerjob-worker-spring-boot-starter 3.3.1依赖时启动项目出现NoClassDefFoundError错误
是不能同时引入么？
新建了一个本地仓库，重新下载源码的依赖，发现比如jackson有两个版本的依赖被下载下来（2.10.3和2.11.2）

**Comment by KFCFans** [comment]
这应该是 powerjob 的 jackson 版本和你项目中的 Jackson 版本冲突了吧🤔
你可以贴个依赖树看看
mvn dependency:tree

**Comment by anxinyh** [comment]
> 这应该是 powerjob 的 jackson 版本和你项目中的 Jackson 版本冲突了吧🤔
> 你可以贴个依赖树看看
> mvn dependency:tree

找到问题了，
文档里给出的依赖代码导致出现这个问题，去掉下面这段标签就好了
<exclusions>
    <exclusion>
      <groupId>com.typesafe.akka</groupId>
      <artifactId>*</artifactId>
    </exclusion>
  </exclusions>
另外，我看文档里说openApi的运行任务支持延迟运行，并且说可以替代延迟队列消息，想问一下，如果我用openApi创建了十万个延迟时间不等的任务，相比于延迟队列，有性能或其他方面的负面影响吗？（比如rabbitmq配合延迟队列插件后的延迟消息效果）

**Comment by KFCFans** [comment]
1. 需要保证 powerjob-server 有足够内存
2. 性能方面，powerjob理论上更有，毕竟是专业调度

anxinyh <notifications@github.com>于2020年10月22日 周四下午5:35写道：
