### ISSUE TITLE
API混合使用问题咨询

### ISSUE THREAD

**Issue by jjnnzb** [KFCFans/PowerJob#91]
## Question
业务里使用了RunJob的API `ResultDTO<Long> runJob(Long jobId)`，调用成功拿到instanceId。此时任务已经在执行之中了，不一定执行结束且执行成功，而业务要求拿到最终的执行状态（成功与否，超过配置的时间也算作失败）。
目前我的想法是设置一个固定的等待时间，到那个点凭借instanceId调用 `ResultDTO<Integer> fetchInstanceStatus(Long instanceId)`获取当时的状态。但是这种实现方法是不是不太优雅？
我如何优雅地实现这个需求呢？

**Comment by jjnnzb** [comment]
其实出发点，就是想复用一下任务的执行逻辑，统一走PowerJob这边打日志，在线可视，可以把公共逻辑抽出来形成一个单独的service的

**Comment by KFCFans** [comment]
这个可能没什么太好的方法，我自己其实也有这种类似的需求。
单独弄了张表把 instanceId 记下来，然后定时轮询查执行结果

Jining Jiang <notifications@github.com>于2020年10月27日 周二下午4:27写道：

**Comment by KFCFans** [comment]
考虑做一个回调，API 大概长这样

runJob(instanceId, params, delay, (success, result) -> {
// biz code
});

**Comment by KFCFans** [comment]
仔细想了下也不好实现
Zookeeper 的回调是广播，所以不需要考虑 HA 和 指定执行的情况。
但 PowerJob 需要精确回调到请求发起方的机器，这个很难保证可靠性，所以还是算了...

自行在 Job 执行完的时候显式调用某个方法作为“回调”吧。
