### ISSUE TITLE
saveJob data的返回值类型为 Integer, 而非 Long

### ISSUE THREAD

**Issue by lemos1235** [KFCFans/PowerJob#93]
**Describe the bug**
类型转换异常。
powerjob-client 调用 saveJob接口后，返回的 jobId 类型为 Integer，而不是 Long，造成类型转换失败！

**Environment**
 - PowerJob Version: 3.3.1
 - Java Version: OpenJDK 8
 - OS: windows10

**Screenshots**
![image](https://user-images.githubusercontent.com/23135552/98099561-b0995d00-1eca-11eb-8e58-33a59bcb6ae7.png)

**Comment by KFCFans** [comment]
可能和序列化和反序列化有关，可以先 `Long.valueOf(String.valueOf(result.getData()))` 解决下

**Comment by KFCFans** [comment]
FastJSON 未使用 TypeReference 进行范型序列化导致。
感谢反馈，下个版本修复。

**Comment by KFCFans** [comment]
v3.3.2 已修复
