### ISSUE TITLE
V3.3.1长时间的广播任务动态上线异常

### ISSUE THREAD

**Issue by junyan-zg** [KFCFans/PowerJob#96]
![image](https://user-images.githubusercontent.com/15311002/98345244-5d044c00-204f-11eb-879c-386f77ac7be5.png)
![image](https://user-images.githubusercontent.com/15311002/98345351-845b1900-204f-11eb-84de-b37615d4297b.png)
**启动第一个worker，正常运行：**
![image](https://user-images.githubusercontent.com/15311002/98345460-aa80b900-204f-11eb-95f9-101569a67e09.png)
**启动第二个worker，即使几分钟后任务也没起来，界面输出没变化**
![image](https://user-images.githubusercontent.com/15311002/98345460-aa80b900-204f-11eb-95f9-101569a67e09.png)

**附上两边日志：**
**worker1**
![image](https://user-images.githubusercontent.com/15311002/98346103-7ce83f80-2050-11eb-933a-be722953d52d.png)

**worker2**
![image](https://user-images.githubusercontent.com/15311002/98346153-896c9800-2050-11eb-823c-cef866c44277.png)

**我看了与V3.3.0的代码对比，大概是因为dispatched 0 tasks 始终为0的原因**

**感谢大佬！**

**Comment by KFCFans** [comment]
应该是你没理解动态上线的含义。
对于已经开始运行的广播任务来说，任务派发那个节点有几台机器就是几台机器，这个过程是不可能有动态上线的。
动态上线体现在下一次开始时，master 节点会根据当前的 worker 集群重新派发任务。

你这个 case，上来就是 sleep 了 1000S，第一个任务实例都没结束，当然看不到动态上线了。

**Comment by junyan-zg** [comment]
好的，假设要个性化实现的话，会不会更复杂，希望指点下

**Comment by KFCFans** [comment]
我觉得你要思考下你这个需求是否合理。
从语义的角度来讲，广播执行就是让每一次调度时所有存活的机器都执行某个操作，那个时刻 offline 的机器就不该参与本次操作，需要等到下次调度再执行。

你这样就相当于破坏了广播执行的语义，和每台机器本地起个线程定时跑没什么区别了。
不太推荐那样使用，建议考虑下场景是否合适，需求是否合理。
