### ISSUE TITLE
任务执行感觉对不上实例

### ISSUE THREAD

**Issue by hjjoe1213123** [KFCFans/PowerJob#97]
## Question
场景：
192.168.1.246 taskService
                      -TaskStartJob
                      -TaskTimeOutJob
192.168.1.191 otherService
                      -otherJob

控制台开启TaskStartJob执行，执行结果：TaskTracker 地址: 192.168.1.191:27777，任务结果: com.github.kfcfans.powerjob.common.PowerJobException: fetch Processor failed

所有任务均未指定机器IP
TaskStartJob理论上应该跑246才对，为何会去找191执行这个任务呢？

**Comment by KFCFans** [comment]
请仔细阅读文档。

既然部署代码不一致，其对应的 Java 项目显然也不一致，按照 PowerJob 的规范需要通过 AppName 隔离。同一个 AppName 下的实例都需要保证幂等。

powerjob-server 调度时并不会判断 worker 是否存在该执行器，通过 AppName 的隔离已经默认 worker 存在该 Processor。
