### ISSUE TITLE
Arbitrary password modification vulnerability

### ISSUE THREAD

**Issue by Gitaddy** [KFCFans/PowerJob#99]
存在任意用户修改密码漏洞（Arbitrary password modification vulnerability）
官方试用地址：http://try.powerjob.tech/#/welcome
注册账号1：test1 / 123456
注册账号2：test2 / 123456
![1](https://user-images.githubusercontent.com/37129047/99079537-0d97c000-25fb-11eb-8c06-dd9c342d4113.png)
![2](https://user-images.githubusercontent.com/37129047/99079578-1be5dc00-25fb-11eb-9186-02b57f65b1fc.png)
进入账号1：
![3](https://user-images.githubusercontent.com/37129047/99079600-23a58080-25fb-11eb-94f4-eea9ee8170d2.png)
修改用户密码：
![4](https://user-images.githubusercontent.com/37129047/99079638-2e601580-25fb-11eb-9e5e-880460446c7c.png)
![5](https://user-images.githubusercontent.com/37129047/99079663-33bd6000-25fb-11eb-854b-bafb1281d814.png)
不存在身份校验等凭证，直接可以修改用户test2的密码
这里仅存的就是id，但是由于是直接递增的，所以test2的id应该是73
![6](https://user-images.githubusercontent.com/37129047/99079681-391aaa80-25fb-11eb-894a-f257ac7b7e9d.png)
最后登录成功：
![7](https://user-images.githubusercontent.com/37129047/99079698-3f108b80-25fb-11eb-844f-44197dfe6c12.png)
![8](https://user-images.githubusercontent.com/37129047/99079706-420b7c00-25fb-11eb-9f32-4c96fe1debeb.png)

**Comment by KFCFans** [comment]
哈哈哈，不得不说你真的太有极客精神了。
由于 PowerJob 是一个典型的内网系统，在控制台安全性这个层面并没有考虑太多，或者说故意不考虑那么多。
毕竟一旦考虑就得顺带着考虑权限控制等东西，这会让 powerjob-server 变得非常不存粹。

不过既然你都那么辛苦的找出问题了，下个版本我就稍微强化下控制台的安全性吧...至少加个密码校验。

最后，十分感谢那么细致入微的排查和反馈！
